import React, { useEffect, useState } from "react";
import { BudgetItem, FinancialAccount, FinancialAccountType, Goal, HOUSEHOLD_OWNER, Transaction } from "../domain/types";
import { CategorySelector, MoneyInput, monthLabel, OwnerSelector } from "./Controls";
import { createId } from "../domain/id";
import { useBudgyStore } from "../store/BudgyStore";
import { useAuth } from "../auth/AuthProvider";
import { accountBalances, suggestBudgetItem, transactionDefaults } from "../domain/accounts";
import { Dialog } from "./Dialog";
import { ownerLabel } from "../domain/ownership";
import { useHousehold } from "../application/HouseholdContext";
import { clearTransactionDraft, readTransactionDraft, transactionDraftKey, writeTransactionDraft } from "../application/transactionDraft";
import{applyIncomeSource,isValidTransaction,sanitizeTransaction,switchTransactionType}from"../domain/transactions";
import{availableBudgetMonths,BudgetMonthMode,changeTransactionDate,chooseBudgetMonth,ensureBudgetMonth,inheritedMonth,isBudgetPlanningType,monthFromDate,transactionBudgetMonth}from"../domain/months";
import{allocationPurpose,matchDebtPaymentAllocation}from"../domain/allocations";
import{formatMoney}from"../domain/money";

const accountTypes:Record<FinancialAccountType,string>={current_account:"Current account",savings_account:"Savings account",credit_card:"Credit card",cash:"Cash",other:"Other"};
export const AccountForm:React.FC<{account?:FinancialAccount;onSave:(account:FinancialAccount)=>void;onCancel:()=>void}>=({account:initial,onSave,onCancel})=>{const{session}=useAuth();const[value,setValue]=useState<FinancialAccount>(initial??{id:createId(),name:"",owner:session!.user.id,type:"current_account",currency:"GBP",openingBalance:0,isActive:true});return <form className="budgy-form" onSubmit={(event)=>{event.preventDefault();if(value.name.trim())onSave({...value,name:value.name.trim()});}}><label className="budgy-field"><span>Account name</span><input autoFocus required value={value.name} onChange={(event)=>setValue({...value,name:event.target.value})} placeholder="Main current account"/></label><div className="budgy-form-grid"><label className="budgy-field"><span>Account type</span><select value={value.type} onChange={(event)=>setValue({...value,type:event.target.value as FinancialAccountType})}>{Object.entries(accountTypes).map(([type,label])=><option key={type} value={type}>{label}</option>)}</select></label><OwnerSelector value={value.owner} onChange={(owner)=>setValue({...value,owner})}/><MoneyInput label={value.type==="credit_card"?"Current balance owed":"Opening balance (optional)"} value={value.openingBalance} onChange={(openingBalance)=>setValue({...value,openingBalance})}/>{value.type==="credit_card"&&<><MoneyInput label="Credit limit" value={value.creditLimit??0} onChange={(creditLimit)=>setValue({...value,creditLimit})}/><MoneyInput label="Latest statement balance (optional)" value={value.statementBalance??0} onChange={(statementBalance)=>setValue({...value,statementBalance})}/><label className="budgy-field"><span>Payment due <small>Optional</small></span><input type="date" value={value.paymentDueDate??""} onChange={(event)=>setValue({...value,paymentDueDate:event.target.value||undefined})}/></label></>} {initial&&<label className="budgy-check"><input type="checkbox" checked={value.isActive} onChange={(event)=>setValue({...value,isActive:event.target.checked})}/><span>Available for new transactions</span></label>}</div><div className="budgy-dialog-actions"><button type="button" className="budgy-button budgy-button--quiet" onClick={onCancel}>Cancel</button><button className="budgy-button budgy-button--primary">{initial?"Save account":"Add account"}</button></div></form>;};


export const BudgetItemForm: React.FC<{ item?: BudgetItem; categories: string[]; accounts?:FinancialAccount[]; transactions?:Transaction[]; onSave: (item: BudgetItem) => void; onCancel: () => void }> = ({ item, categories,accounts=[],transactions=[], onSave, onCancel }) => {
  const cards=accountBalances(accounts,transactions).filter((account)=>account.type==="credit_card"&&account.isActive);
  const [value, setValue] = useState<BudgetItem>(item ?? { id: createId(), name: "", group: categories[0], owner: HOUSEHOLD_OWNER, amount: 0, recurring: true,purpose:"spending" });
  const purpose=allocationPurpose(value);
  return <form className="budgy-form" onSubmit={(event) => { event.preventDefault(); if (value.name.trim() && value.amount >= 0&&(purpose!=="debt_payment"||value.linkedAccountId)) onSave({ ...value, name: value.name.trim(),purpose,group:purpose==="spending"?value.group:"Debt payments",trackActuals:true }); }}>
    <label className="budgy-field"><span>Name</span><input autoFocus required value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /></label>
    <label className="budgy-field"><span>What is this money for?</span><select value={purpose} onChange={(event)=>{const next=event.target.value as BudgetItem["purpose"];setValue({...value,purpose:next,linkedAccountId:next==="debt_payment"?value.linkedAccountId??cards[0]?.id:undefined,group:next==="spending"?categories[0]:"Debt payments",name:next==="debt_payment"&&!value.name?`${cards[0]?.name??"Card"} payment`:value.name});}}><option value="spending">Everyday spending</option><option value="debt_payment">Paying down debt</option></select><small>Savings and investing remain in Money for later so they are not counted twice.</small></label>
    <div className="budgy-form-grid"><MoneyInput label={purpose==="debt_payment"?"Amount to put toward it":"Planned amount"} value={value.amount} onChange={(amount) => setValue({ ...value, amount })} required />{purpose==="spending"?<CategorySelector value={value.group} categories={categories} onChange={(group) => setValue({ ...value, group })} />:<label className="budgy-field"><span>Which debt?</span><select required value={value.linkedAccountId??""} onChange={(event)=>{const linkedAccountId=event.target.value||undefined;const card=cards.find((entry)=>entry.id===linkedAccountId);setValue({...value,linkedAccountId,name:value.name||`${card?.name??"Card"} payment`});}}><option value="">Select credit card</option>{cards.map((card)=><option key={card.id} value={card.id}>{card.name} · {formatMoney(card.balance)} owed</option>)}</select>{!cards.length&&<small>Add an active credit card in Money before planning a debt payment.</small>}</label>}<OwnerSelector value={value.owner} onChange={(owner) => setValue({ ...value, owner })} /></div>
    <label className="budgy-check"><input type="checkbox" checked={value.recurring} onChange={(event) => setValue({ ...value, recurring: event.target.checked })} /><span>Repeat this item in new months</span></label>
    {purpose==="spending"&&<label className="budgy-check"><input type="checkbox" checked={value.trackActuals!==false} onChange={(event) => setValue({ ...value, trackActuals: event.target.checked })} /><span>Track transactions against this allowance</span></label>}
    <div className="budgy-dialog-actions"><button className="budgy-button budgy-button--quiet" type="button" onClick={onCancel}>Cancel</button><button className="budgy-button budgy-button--primary" type="submit">Save item</button></div>
  </form>;
};

interface TransactionFormProps { month:string;initialType?:Transaction["type"];initialDestinationAccountId?:string;initialGoalId?:string;initialTransaction?:Transaction;onSave:(value:Transaction)=>void;onCancel:()=>void; }
export const TransactionForm:React.FC<TransactionFormProps>=({month,initialType="expense",initialDestinationAccountId,initialGoalId,initialTransaction,onSave,onCancel})=>{
  const{data,plan:activePlan,updateData}=useBudgyStore();const{session}=useAuth();const household=useHousehold();const userId=session!.user.id;
  const defaults=transactionDefaults(userId,activePlan.budget,data.accounts,data.categories[0]);const today=new Date().toISOString().slice(0,10);const[accountOpen,setAccountOpen]=useState(false);const[error,setError]=useState("");const draftKey=transactionDraftKey(userId,household.household.id);
  const[value,setValue]=useState<Transaction>(()=>{
    if(initialTransaction)return{...initialTransaction,budgetMonth:isBudgetPlanningType(initialTransaction.type)?transactionBudgetMonth(initialTransaction):undefined};
    const restored=readTransactionDraft(draftKey);
    if(restored&&!initialGoalId){const normalized=sanitizeTransaction(restored);if(normalized.type==="income"&&!data.incomeCategories.includes(normalized.category??""))return{...normalized,category:data.incomeCategories[0]};if((normalized.type==="expense"||normalized.type==="refund")&&!data.categories.includes(normalized.category??""))return{...normalized,category:data.categories[0],incomeSourceId:undefined};return normalized;}
    const initialGoal=data.goals.find((goal)=>goal.id===initialGoalId);const date=today.startsWith(month)?today:`${month}-01`;const description=initialGoal?`Contribution to ${initialGoal.name}`:initialType==="transfer"?"Transfer":initialType==="credit_card_payment"?"Credit card payment":"";
    const debtAllocation=initialType==="credit_card_payment"?matchDebtPaymentAllocation(activePlan,initialDestinationAccountId):undefined;
    return{id:createId(),type:initialType,amount:0,description,category:initialType==="income"?data.incomeCategories[0]:initialType==="expense"||initialType==="refund"?data.categories[0]:undefined,owner:defaults.owner,date,budgetMonth:isBudgetPlanningType(initialType)?monthFromDate(date):undefined,note:"",actorUserId:userId,accountId:defaults.accountId,destinationAccountId:initialGoal?.fundingAccountId??initialDestinationAccountId,savingsGoalId:initialGoal?.id,budgetItemId:initialType==="expense"||initialType==="refund"?defaults.budgetItemId:debtAllocation?.id};
  });
  const[budgetMonthMode,setBudgetMonthMode]=useState<BudgetMonthMode>(()=>initialTransaction?"manual":value.budgetMonth&&value.budgetMonth!==monthFromDate(value.date)?"manual":"auto");
  const selectedMonth=transactionBudgetMonth(value)??month;const selectedPlan=data.months[selectedMonth]??inheritedMonth(data,selectedMonth);const monthOptions=availableBudgetMonths(data,value.date);
  useEffect(()=>{if(isBudgetPlanningType(value.type)&&!data.months[selectedMonth])updateData((current)=>ensureBudgetMonth(current,selectedMonth,selectedPlan));},[data.months,selectedMonth,selectedPlan,updateData,value.type]);
  useEffect(()=>{if((value.type==="expense"||value.type==="refund")&&value.budgetItemId&&!selectedPlan.budget.some((item)=>item.id===value.budgetItemId&&item.trackActuals!==false)){const suggested=suggestBudgetItem(value.owner,value.category??"",selectedPlan.budget);setValue((current)=>({...current,budgetItemId:suggested?.id}));}},[selectedPlan.budget,value.type,value.budgetItemId,value.owner,value.category]);
  useEffect(()=>{if(!initialTransaction)writeTransactionDraft(draftKey,value);},[draftKey,initialTransaction,value]);
  const discard=()=>{if(!initialTransaction)clearTransactionDraft(draftKey);onCancel();};
  const changeType=(type:Transaction["type"])=>{const next=switchTransactionType(value,type,data.categories[0]??"",data.incomeCategories[0]??"");const canUseCredit=type!=="income"&&type!=="credit_card_payment";const account=data.accounts.find((entry)=>entry.id===next.accountId&&entry.isActive&&(canUseCredit||entry.type!=="credit_card"));const nextMonth=transactionBudgetMonth(next);const nextPlan=nextMonth?(data.months[nextMonth]??inheritedMonth(data,nextMonth)):activePlan;if(nextMonth)updateData((current)=>ensureBudgetMonth(current,nextMonth,nextPlan));const destinationAccountId=type==="credit_card_payment"?initialDestinationAccountId:undefined;setValue({...next,accountId:account?.id??data.accounts.find((entry)=>entry.isActive&&(canUseCredit||entry.type!=="credit_card"))?.id,destinationAccountId,budgetItemId:type==="expense"||type==="refund"?suggestBudgetItem(next.owner,next.category??"",nextPlan.budget)?.id:type==="credit_card_payment"?matchDebtPaymentAllocation(nextPlan,destinationAccountId)?.id:undefined});if(isBudgetPlanningType(type))setBudgetMonthMode("auto");setError("");};
  const updateOwner=(owner:string)=>setValue({...value,owner,budgetItemId:value.type==="expense"||value.type==="refund"?suggestBudgetItem(owner,value.category??"",selectedPlan.budget)?.id:value.budgetItemId});
  const updateCategory=(category:string)=>setValue({...value,category,budgetItemId:value.type==="expense"||value.type==="refund"?suggestBudgetItem(value.owner,category,selectedPlan.budget)?.id:undefined});
  const updateDate=(date:string)=>{if(!date){setValue({...value,date});return;}const next=changeTransactionDate(value,date,budgetMonthMode);const nextMonth=transactionBudgetMonth(next);const nextPlan=nextMonth?(data.months[nextMonth]??inheritedMonth(data,nextMonth)):selectedPlan;if(nextMonth)updateData((current)=>ensureBudgetMonth(current,nextMonth,nextPlan));setValue({...next,budgetItemId:next.type==="expense"||next.type==="refund"?suggestBudgetItem(next.owner,next.category??"",nextPlan.budget)?.id:next.type==="credit_card_payment"?matchDebtPaymentAllocation(nextPlan,next.destinationAccountId)?.id:undefined});};
  const updateBudgetMonth=(budgetMonth:string)=>{const nextPlan=data.months[budgetMonth]??inheritedMonth(data,budgetMonth);updateData((current)=>ensureBudgetMonth(current,budgetMonth,nextPlan));setBudgetMonthMode("manual");setValue((current)=>({...chooseBudgetMonth(current,budgetMonth),budgetItemId:current.type==="expense"||current.type==="refund"?suggestBudgetItem(current.owner,current.category??"",nextPlan.budget)?.id:current.type==="credit_card_payment"?matchDebtPaymentAllocation(nextPlan,current.destinationAccountId)?.id:undefined,incomeSourceId:current.type==="income"?undefined:current.incomeSourceId}));};
  const transfer=value.type==="transfer"||value.type==="credit_card_payment";const classified=isBudgetPlanningType(value.type);const sourceAccounts=data.accounts.filter((account)=>account.isActive&&((value.type!=="income"&&value.type!=="credit_card_payment")||account.type!=="credit_card"));const accountLegend=value.type==="income"||value.type==="refund"?"Paid into":value.type==="transfer"?"From account":"Paid from";
  const submit=(event:React.FormEvent)=>{event.preventDefault();const clean=sanitizeTransaction(value);if((clean.type==="expense"||clean.type==="refund")&&clean.budgetItemId&&!selectedPlan.budget.some((item)=>item.id===clean.budgetItemId&&item.trackActuals!==false&&allocationPurpose(item)==="spending")){setError("That monthly allowance is no longer available. Choose another allowance or select ‘No monthly allowance’.");return;}if(clean.type==="credit_card_payment"&&clean.budgetItemId&&!selectedPlan.budget.some((item)=>item.id===clean.budgetItemId&&allocationPurpose(item)==="debt_payment"&&item.linkedAccountId===clean.destinationAccountId)){setError("That payment plan does not match this card and month. Choose the matching plan or no planned payment.");return;}if(!isValidTransaction(clean,{expenseCategories:data.categories,incomeCategories:data.incomeCategories,accounts:data.accounts,goals:data.goals,budgetItems:selectedPlan.budget})){setError("Complete the required fields for this transaction type.");return;}clearTransactionDraft(draftKey);onSave(clean);};
  return <><form className="budgy-form" onSubmit={submit}>
    <div className="budgy-segmented"><button type="button" className={value.type==="expense"?"is-active":""} onClick={()=>changeType("expense")}>Expense</button><button type="button" className={value.type==="refund"?"is-active":""} onClick={()=>changeType("refund")}>Refund</button><button type="button" className={value.type==="income"?"is-active":""} onClick={()=>changeType("income")}>Income</button><button type="button" className={value.type==="transfer"?"is-active":""} onClick={()=>changeType("transfer")}>Transfer</button><button type="button" className={value.type==="credit_card_payment"?"is-active":""} onClick={()=>changeType("credit_card_payment")}>Card payment</button></div>
    {classified&&<label className="budgy-field"><span>{value.type==="income"?"Description":"Merchant or description"}</span><input autoFocus required value={value.description} onChange={(event)=>setValue({...value,description:event.target.value})} placeholder={value.type==="income"?"September salary":""}/></label>}
    <div className="budgy-form-grid">
      <MoneyInput label="Amount" value={value.amount} onChange={(amount)=>setValue({...value,amount})} required/>
      {(value.type==="expense"||value.type==="refund")&&<CategorySelector value={value.category??""} categories={data.categories} onChange={updateCategory}/>}
      {value.type==="income"&&<><CategorySelector label="Income type" value={value.category??""} categories={data.incomeCategories} onChange={(category)=>setValue({...value,category})}/><label className="budgy-field"><span>Source</span><select value={value.incomeSourceId??""} onChange={(event)=>{const source=selectedPlan.income.find((entry)=>entry.id===event.target.value);setValue(source?applyIncomeSource(value,source):{...value,incomeSourceId:undefined});}}><option value="">No planned source</option>{selectedPlan.income.map((source)=><option key={source.id} value={source.id}>{source.name}</option>)}</select></label></>}
      {classified&&<OwnerSelector value={value.owner} onChange={updateOwner}/>}<fieldset className="budgy-account-picker"><legend>{accountLegend}</legend>{sourceAccounts.length?<div>{sourceAccounts.map((account)=><label key={account.id}><input type="radio" name="payment-account" required checked={value.accountId===account.id} onChange={()=>setValue({...value,accountId:account.id,destinationAccountId:value.destinationAccountId===account.id?undefined:value.destinationAccountId})}/><span><b>{account.name}</b><small>{ownerLabel(account.owner,data.members)}</small></span></label>)}</div>:<p>You haven’t added a suitable account yet.</p>}<button type="button" className="budgy-add-account-link" onClick={()=>setAccountOpen(true)}>+ {sourceAccounts.length?"Add an account":"Add your first account"}</button></fieldset>
      {transfer&&<label className="budgy-field"><span>{value.type==="credit_card_payment"?"Credit card":"To account"}</span><select required value={value.destinationAccountId??""} onChange={(event)=>{const destinationAccountId=event.target.value||undefined;const linkedGoal=data.goals.find((goal)=>goal.id===value.savingsGoalId);setValue({...value,destinationAccountId,savingsGoalId:linkedGoal&&linkedGoal.fundingAccountId===destinationAccountId?linkedGoal.id:undefined,budgetItemId:value.type==="credit_card_payment"?matchDebtPaymentAllocation(selectedPlan,destinationAccountId)?.id:value.budgetItemId});}}><option value="">Select destination</option>{data.accounts.filter((account)=>account.isActive&&account.id!==value.accountId&&(value.type!=="credit_card_payment"||account.type==="credit_card")).map((account)=><option key={account.id} value={account.id}>{account.name}</option>)}</select></label>}
      {value.type==="transfer"&&<label className="budgy-field"><span>Saving towards <small>Optional</small></span><select value={value.savingsGoalId??""} onChange={(event)=>{const goal=data.goals.find((entry)=>entry.id===event.target.value);setValue({...value,savingsGoalId:goal?.id,destinationAccountId:goal?.fundingAccountId??value.destinationAccountId,description:goal?`Contribution to ${goal.name}`:value.description});}}><option value="">General account transfer</option>{data.goals.filter((goal)=>goal.fundingAccountId&&data.accounts.some((account)=>account.id===goal.fundingAccountId&&account.isActive&&account.type==="savings_account")).map((goal)=><option key={goal.id} value={goal.id}>{goal.name} · {data.accounts.find((account)=>account.id===goal.fundingAccountId)?.name}</option>)}</select></label>}
      {(value.type==="expense"||value.type==="refund")&&<label className="budgy-field"><span>Counts against</span><select value={value.budgetItemId??""} onChange={(event)=>setValue({...value,budgetItemId:event.target.value||undefined})}><option value="">No monthly allowance</option>{selectedPlan.budget.filter((item)=>item.trackActuals!==false&&allocationPurpose(item)==="spending").map((item)=><option key={item.id} value={item.id}>{item.name} · {item.group}</option>)}</select></label>}
      {value.type==="credit_card_payment"&&<label className="budgy-field"><span>Counts toward <small>Optional</small></span><select value={value.budgetItemId??""} onChange={(event)=>setValue({...value,budgetItemId:event.target.value||undefined})}><option value="">No planned payment</option>{selectedPlan.budget.filter((item)=>allocationPurpose(item)==="debt_payment"&&item.linkedAccountId===value.destinationAccountId).map((item)=><option key={item.id} value={item.id}>{item.name} · {formatMoney(item.amount)} planned</option>)}</select><small>Budgy suggests the matching payment plan for this card.</small></label>}
      <label className="budgy-field"><span>Date</span><input type="date" required value={value.date} onChange={(event)=>updateDate(event.target.value)}/></label>
      {classified&&<label className="budgy-field"><span>Counts toward</span><select required value={selectedMonth} onChange={(event)=>updateBudgetMonth(event.target.value)}>{monthOptions.map((option)=><option key={option} value={option}>{monthLabel(option)}</option>)}</select><small>The monthly budget this {value.type==="income"?"income":"expense"} belongs to. {budgetMonthMode==="auto"?"Updates with the date until you choose a month.":"Your month choice will stay when the date changes."}</small></label>}
    </div>
    <label className="budgy-field"><span>Note <small>Optional</small></span><textarea rows={3} value={value.note} onChange={(event)=>setValue({...value,note:event.target.value})}/></label>{error&&<p className="budgy-auth-message" role="alert">{error}</p>}<div className="budgy-dialog-actions"><button className="budgy-button budgy-button--quiet" type="button" onClick={discard}>{initialTransaction?"Cancel":"Discard"}</button><button className="budgy-button budgy-button--primary" type="submit">{initialTransaction?"Save changes":"Add transaction"}</button></div>
  </form><Dialog open={accountOpen} title="Add account" description="Your transaction details will stay exactly as entered." onClose={()=>setAccountOpen(false)}><AccountForm onCancel={()=>setAccountOpen(false)} onSave={(newAccount)=>{updateData((current)=>({...current,accounts:[...current.accounts,newAccount]}));setValue((current)=>({...current,accountId:newAccount.id}));setAccountOpen(false);}}/></Dialog></>;
};

export const GoalForm: React.FC<{ goal?: Goal; onSave: (goal: Goal) => void; onCancel: () => void }> = ({ goal, onSave, onCancel }) => {
  const {data}=useBudgyStore();
  const savingsAccounts=data.accounts.filter((account)=>account.isActive&&account.type==="savings_account");
  const [value, setValue] = useState<Goal>(goal ?? { id: createId(), name: "", icon: "◎", targetAmount: 0, currentAmount: 0, targetDate: "2027-09-01", monthlyContribution: 0, description: "",fundingAccountId:savingsAccounts[0]?.id });
  return <form className="budgy-form" onSubmit={(event) => { event.preventDefault(); if (value.name.trim() && value.targetAmount > 0) onSave(value); }}>
    <div className="budgy-form-grid"><label className="budgy-field"><span>Goal name</span><input autoFocus required value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /></label><label className="budgy-field"><span>Icon</span><select value={value.icon} onChange={(event) => setValue({ ...value, icon: event.target.value })}><option>◎</option><option>⌂</option><option>✈</option><option>♡</option><option>◈</option></select></label><MoneyInput label="Target amount" value={value.targetAmount} onChange={(targetAmount) => setValue({ ...value, targetAmount })} /><MoneyInput label="Starting amount already saved" value={value.currentAmount} onChange={(currentAmount) => setValue({ ...value, currentAmount })} /><MoneyInput label="Planned monthly contribution" value={value.monthlyContribution} onChange={(monthlyContribution) => setValue({ ...value, monthlyContribution })} /><label className="budgy-field"><span>Target date</span><input type="date" required value={value.targetDate} onChange={(event) => setValue({ ...value, targetDate: event.target.value })} /></label><label className="budgy-field"><span>Saved in</span><select required value={value.fundingAccountId??""} onChange={(event)=>setValue({...value,fundingAccountId:event.target.value||undefined})}><option value="">Select savings account</option>{savingsAccounts.map((account)=><option key={account.id} value={account.id}>{account.name}</option>)}</select><small>{savingsAccounts.length?"Contributions will be transferred into this account.":"Add a savings account from Money before saving this goal."}</small></label></div>
    <label className="budgy-field"><span>Description <small>Optional</small></span><textarea rows={3} value={value.description} onChange={(event) => setValue({ ...value, description: event.target.value })} /></label>
    <div className="budgy-dialog-actions"><button className="budgy-button budgy-button--quiet" type="button" onClick={onCancel}>Cancel</button><button className="budgy-button budgy-button--primary" type="submit">Save goal</button></div>
  </form>;
};
