import React, { useState } from "react";
import { BudgetItem, Goal, HOUSEHOLD_OWNER, Transaction } from "../domain/types";
import { CategorySelector, MoneyInput, OwnerSelector } from "./Controls";
import { createId } from "../domain/id";
import { useBudgyStore } from "../store/BudgyStore";
import { useAuth } from "../auth/AuthProvider";
import { suggestBudgetItem, transactionDefaults } from "../domain/accounts";


export const BudgetItemForm: React.FC<{ item?: BudgetItem; categories: string[]; onSave: (item: BudgetItem) => void; onCancel: () => void }> = ({ item, categories, onSave, onCancel }) => {
  const [value, setValue] = useState<BudgetItem>(item ?? { id: createId(), name: "", group: categories[0], owner: HOUSEHOLD_OWNER, amount: 0, recurring: true });
  return <form className="budgy-form" onSubmit={(event) => { event.preventDefault(); if (value.name.trim() && value.amount >= 0) onSave({ ...value, name: value.name.trim() }); }}>
    <label className="budgy-field"><span>Name</span><input autoFocus required value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /></label>
    <div className="budgy-form-grid"><MoneyInput label="Planned amount" value={value.amount} onChange={(amount) => setValue({ ...value, amount })} required /><CategorySelector value={value.group} categories={categories} onChange={(group) => setValue({ ...value, group })} /><OwnerSelector value={value.owner} onChange={(owner) => setValue({ ...value, owner })} /></div>
    <label className="budgy-check"><input type="checkbox" checked={value.recurring} onChange={(event) => setValue({ ...value, recurring: event.target.checked })} /><span>Repeat this item in new months</span></label>
    <label className="budgy-check"><input type="checkbox" checked={value.trackActuals!==false} onChange={(event) => setValue({ ...value, trackActuals: event.target.checked })} /><span>Track transactions against this allowance</span></label>
    <div className="budgy-dialog-actions"><button className="budgy-button budgy-button--quiet" type="button" onClick={onCancel}>Cancel</button><button className="budgy-button budgy-button--primary" type="submit">Save item</button></div>
  </form>;
};

export const TransactionForm: React.FC<{ month: string; categories: string[]; initialType?:Transaction["type"]; initialDestinationAccountId?:string; onSave: (value: Transaction) => void; onCancel: () => void }> = ({ month, categories, initialType="expense", initialDestinationAccountId, onSave, onCancel }) => {
  const {data,plan}=useBudgyStore();const{session}=useAuth();const userId=session!.user.id;const defaults=transactionDefaults(userId,plan.budget,data.accounts,categories[0]);const today=new Date().toISOString().slice(0,10);
  const [value, setValue] = useState<Transaction>({ id: createId(), type: initialType, amount: 0, description: "", category: categories[0], owner: defaults.owner, date: today.startsWith(month)?today:`${month}-01`, note: "", actorUserId:userId,accountId:defaults.accountId,destinationAccountId:initialDestinationAccountId,budgetItemId:defaults.budgetItemId });
  const updateOwner=(owner:string)=>setValue({...value,owner,budgetItemId:suggestBudgetItem(owner,value.category,plan.budget)?.id});
  const updateCategory=(category:string)=>setValue({...value,category,budgetItemId:suggestBudgetItem(value.owner,category,plan.budget)?.id});
  const transfer=value.type==="transfer"||value.type==="credit_card_payment";
  return <form className="budgy-form" onSubmit={(event) => { event.preventDefault(); if (value.description.trim() && value.amount > 0) onSave(value); }}>
    <div className="budgy-segmented"><button type="button" className={value.type === "expense" ? "is-active" : ""} onClick={() => setValue({ ...value, type: "expense" })}>Expense</button><button type="button" className={value.type === "income" ? "is-active" : ""} onClick={() => setValue({ ...value, type: "income",budgetItemId:undefined })}>Income</button><button type="button" className={value.type === "transfer" ? "is-active" : ""} onClick={() => setValue({ ...value, type: "transfer",budgetItemId:undefined })}>Transfer</button><button type="button" className={value.type === "credit_card_payment" ? "is-active" : ""} onClick={() => setValue({ ...value, type: "credit_card_payment",budgetItemId:undefined })}>Card payment</button></div>
    {value.type==="expense"&&<OwnerSelector label="Who?" value={value.owner} onChange={updateOwner}/>} 
    <label className="budgy-field"><span>Merchant or description</span><input autoFocus required value={value.description} onChange={(event) => setValue({ ...value, description: event.target.value })} /></label>
    <div className="budgy-form-grid"><MoneyInput label="Amount" value={value.amount} onChange={(amount) => setValue({ ...value, amount })} required />{!transfer&&<CategorySelector value={value.category} categories={categories} onChange={updateCategory}/>}<label className="budgy-field"><span>{value.type==="income"?"Paid into":"Paid from"}</span><select required value={value.accountId??""} onChange={(event)=>setValue({...value,accountId:event.target.value||undefined})}><option value="">Select account</option>{data.accounts.filter((account)=>account.isActive&&(value.type!=="credit_card_payment"||account.type!=="credit_card")).map((account)=><option key={account.id} value={account.id}>{account.name}</option>)}</select></label>{transfer&&<label className="budgy-field"><span>{value.type==="credit_card_payment"?"Credit card":"Transfer to"}</span><select required value={value.destinationAccountId??""} onChange={(event)=>setValue({...value,destinationAccountId:event.target.value||undefined})}><option value="">Select destination</option>{data.accounts.filter((account)=>account.isActive&&account.id!==value.accountId&&(value.type!=="credit_card_payment"||account.type==="credit_card")).map((account)=><option key={account.id} value={account.id}>{account.name}</option>)}</select></label>}{value.type==="expense"&&<label className="budgy-field"><span>Count against</span><select value={value.budgetItemId??""} onChange={(event)=>setValue({...value,budgetItemId:event.target.value||undefined})}><option value="">No monthly allowance</option>{plan.budget.filter((item)=>item.trackActuals!==false).map((item)=><option key={item.id} value={item.id}>{item.name} · {item.group}</option>)}</select></label>}<label className="budgy-field"><span>Date</span><input type="date" required value={value.date} onChange={(event) => setValue({ ...value, date: event.target.value })} /></label></div>
    <label className="budgy-field"><span>Note <small>Optional</small></span><textarea rows={3} value={value.note} onChange={(event) => setValue({ ...value, note: event.target.value })} /></label>
    <div className="budgy-dialog-actions"><button className="budgy-button budgy-button--quiet" type="button" onClick={onCancel}>Cancel</button><button className="budgy-button budgy-button--primary" type="submit">Add transaction</button></div>
  </form>;
};

export const GoalForm: React.FC<{ goal?: Goal; onSave: (goal: Goal) => void; onCancel: () => void }> = ({ goal, onSave, onCancel }) => {
  const [value, setValue] = useState<Goal>(goal ?? { id: createId(), name: "", icon: "◎", targetAmount: 0, currentAmount: 0, targetDate: "2027-09-01", monthlyContribution: 0, description: "" });
  return <form className="budgy-form" onSubmit={(event) => { event.preventDefault(); if (value.name.trim() && value.targetAmount > 0) onSave(value); }}>
    <div className="budgy-form-grid"><label className="budgy-field"><span>Goal name</span><input autoFocus required value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /></label><label className="budgy-field"><span>Icon</span><select value={value.icon} onChange={(event) => setValue({ ...value, icon: event.target.value })}><option>◎</option><option>⌂</option><option>✈</option><option>♡</option><option>◈</option></select></label><MoneyInput label="Target amount" value={value.targetAmount} onChange={(targetAmount) => setValue({ ...value, targetAmount })} /><MoneyInput label="Current amount" value={value.currentAmount} onChange={(currentAmount) => setValue({ ...value, currentAmount })} /><MoneyInput label="Monthly contribution" value={value.monthlyContribution} onChange={(monthlyContribution) => setValue({ ...value, monthlyContribution })} /><label className="budgy-field"><span>Target date</span><input type="date" required value={value.targetDate} onChange={(event) => setValue({ ...value, targetDate: event.target.value })} /></label></div>
    <label className="budgy-field"><span>Description <small>Optional</small></span><textarea rows={3} value={value.description} onChange={(event) => setValue({ ...value, description: event.target.value })} /></label>
    <div className="budgy-dialog-actions"><button className="budgy-button budgy-button--quiet" type="button" onClick={onCancel}>Cancel</button><button className="budgy-button budgy-button--primary" type="submit">Save goal</button></div>
  </form>;
};
