import React,{useEffect,useMemo,useRef,useState}from"react";
import{useAuth}from"../auth/AuthProvider";
import{calculateHouseholdSummary}from"../domain/budget";
import{createId}from"../domain/id";
import{formatMoney}from"../domain/money";
import{BudgetItem,FinancialAccount,HOUSEHOLD_OWNER,IncomeSource}from"../domain/types";
import{useHousehold}from"../application/HouseholdContext";
import{useBudgyStore}from"../store/BudgyStore";
import{MoneyInput}from"./Controls";
import{AccountForm}from"./Forms";
import{householdRepository}from"../repositories/householdRepository";

type HouseholdMode="solo"|"partner"|"household";
type OutgoingOption={name:string;group:string;section:string};
interface SetupDraft{householdMode:HouseholdMode;householdName:string;income:IncomeSource[];outgoings:BudgetItem[];savings:number;}

const outgoingOptions:OutgoingOption[]=[
  {section:"Home",name:"Rent / Mortgage",group:"Home"},{section:"Home",name:"Council tax",group:"Home"},{section:"Home",name:"Electricity / Gas",group:"Home"},{section:"Home",name:"Water",group:"Home"},{section:"Home",name:"Internet",group:"Home"},
  {section:"Everyday",name:"Groceries",group:"Food"},{section:"Everyday",name:"Transport",group:"Transport"},{section:"Everyday",name:"Personal spending",group:"Personal"},
  {section:"Financial",name:"Debt repayments",group:"Personal"},{section:"Financial",name:"Insurance",group:"Personal"},
  {section:"Lifestyle",name:"Subscriptions",group:"Subscriptions"},{section:"Lifestyle",name:"Holidays / Travel",group:"Future plans"},
  {section:"Family",name:"Childcare",group:"Personal"},{section:"Family",name:"Family support / gifts",group:"Giving"},{section:"Other",name:"Other regular expense",group:"Personal"},
];
const normalize=(value:string)=>value.trim().toLocaleLowerCase();
const aliases:Record<string,string[]>={"rent / mortgage":["rent","mortgage"],"electricity / gas":["electricity","gas"],"internet":["wifi","wi-fi","internet"],"holidays / travel":["holidays / travel fund","travel"]};
const matchesOption=(item:BudgetItem,option:OutgoingOption)=>[option.name,...(aliases[normalize(option.name)]??[])].some((name)=>normalize(item.name)===normalize(name));
const storageKey=(userId:string,householdId:string,month:string)=>`budgy:guided-setup:${userId}:${householdId}:${month}`;
const loadDraft=(key:string,fallback:SetupDraft)=>{try{const value=sessionStorage.getItem(key);return value?{...fallback,...JSON.parse(value)}as SetupDraft:fallback;}catch{return fallback;}};
const PlanSummary:React.FC<{income:IncomeSource[];outgoings:BudgetItem[];savings:number}>=({income,outgoings,savings})=>{
  const summary=calculateHouseholdSummary({householdName:"",income,budget:outgoings,savings});
  return <aside className="budgy-setup-summary" aria-label="Monthly plan summary"><p className="budgy-eyebrow">Monthly plan</p><dl><div><dt>Coming in</dt><dd>{formatMoney(summary.income)}</dd></div><div><dt>Monthly commitments</dt><dd>{formatMoney(summary.spending)}</dd></div><div><dt>Saving</dt><dd>{formatMoney(summary.savings)}</dd></div><div className={summary.remaining<0?"is-negative":""}><dt>Left to plan</dt><dd>{formatMoney(summary.remaining)}</dd></div></dl></aside>;
};

interface Props{displayName:string;initialStep:number;orientation:boolean;busy:boolean;error:string;onSaveStep:(step:number,save?:()=>Promise<void>)=>Promise<void>;onSkip:()=>void;onFinish:()=>void;}
const GuidedOnboarding:React.FC<Props>=({displayName,initialStep,orientation,busy,error,onSaveStep,onSkip,onFinish})=>{
  const{session}=useAuth();const household=useHousehold();const{data,month,plan,saveData}=useBudgyStore();const userId=session!.user.id;
  const key=storageKey(userId,household.household.id,month);const initial=useMemo<SetupDraft>(()=>({householdMode:household.members.length>1?"household":"solo",householdName:household.household.name,income:plan.income.map((entry)=>({...entry})),outgoings:plan.budget.map((entry)=>({...entry})),savings:plan.savings}),[household.household.name,household.members.length,plan.income,plan.budget,plan.savings]);
  const[draft,setDraft]=useState(()=>loadDraft(key,initial));const[step,setStep]=useState(()=>orientation?Math.min(Math.max(initialStep,0),3):Math.min(Math.max(initialStep,0),4));const[accountOpen,setAccountOpen]=useState(false);const[accountError,setAccountError]=useState("");const headingRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{try{sessionStorage.setItem(key,JSON.stringify(draft));}catch{/* Draft persistence is best effort. */}},[draft,key]);
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous;};},[]);
  useEffect(()=>{headingRef.current?.focus();},[step]);
  const summary=calculateHouseholdSummary({householdName:draft.householdName,income:draft.income,budget:draft.outgoings,savings:draft.savings});
  const updateIncome=(id:string,update:Partial<IncomeSource>)=>setDraft((current)=>({...current,income:current.income.map((row)=>row.id===id?{...row,...update}:row)}));
  const toggleOutgoing=(option:OutgoingOption)=>setDraft((current)=>{const found=current.outgoings.find((item)=>matchesOption(item,option));return found?{...current,outgoings:current.outgoings.filter((item)=>item.id!==found.id)}:{...current,outgoings:[...current.outgoings,{id:createId(),name:option.name,group:option.group,owner:HOUSEHOLD_OWNER,amount:0,recurring:true,trackActuals:true}]};});
  const savePlan=async(fields:"income"|"outgoings"|"savings")=>saveData((current)=>({...current,householdName:draft.householdName,months:{...current.months,[month]:{...current.months[month],householdName:draft.householdName,...(fields==="income"?{income:draft.income}:fields==="outgoings"?{budget:draft.outgoings}:{savings:draft.savings})}}}));
  const next=async()=>{
    if(orientation){if(step===3){onFinish();return;}try{await onSaveStep(step+1);}catch{return;}setStep((value)=>value+1);return;}
    if(step===4){onFinish();return;}
    const nextStep=step+1;
    try{await onSaveStep(nextStep,async()=>{
      if(step===0){const name=draft.householdName.trim()||`${displayName}'s household`;if(name!==household.household.name)await householdRepository.rename(household.household.id,name);setDraft((current)=>({...current,householdName:name}));}
      if(step===1)await savePlan("income");
      if(step===2)await savePlan("outgoings");
      if(step===3)await savePlan("savings");
    });}catch{return;}
    setStep(nextStep);
  };
  const addIncome=()=>setDraft((current)=>({...current,income:[...current.income,{id:createId(),name:"",category:data.incomeCategories[0]??"Salary",owner:current.income.length?HOUSEHOLD_OWNER:userId,amount:0,recurring:true}]}));
  const selected=(option:OutgoingOption)=>draft.outgoings.find((item)=>matchesOption(item,option));
  const unmatched=draft.outgoings.filter((item)=>!outgoingOptions.some((option)=>matchesOption(item,option)));
  const establishedSummary=calculateHouseholdSummary(plan);
  const progressCount=orientation?4:5;
  return <div className="budgy-onboarding-layer budgy-guided-layer" role="dialog" aria-modal="true" aria-label={`Budgy onboarding, step ${step+1} of ${progressCount}`}><section className="budgy-onboarding-walkthrough budgy-guided-setup"><header><div className="budgy-brand"><span className="budgy-brand-mark">B</span><span className="budgy-brand-name">budgy</span></div><span>Step {step+1} of {progressCount}</span></header><div className="budgy-onboarding-progress" aria-hidden="true" style={{gridTemplateColumns:`repeat(${progressCount},1fr)`}}>{Array.from({length:progressCount},(_,index)=><i key={index} className={index<=step?"is-active":""}/>)}</div><div className="budgy-guided-scroll" ref={headingRef} tabIndex={-1}>
    {orientation?<>
      {step===0&&<section className="budgy-setup-step"><p className="budgy-eyebrow">Welcome</p><h1>Welcome to Budgy, {displayName}</h1><p>You’re joining <b>{household.household.name}</b>. This is the shared money space where your household plans together and sees the same financial picture.</p></section>}
      {step===1&&<section className="budgy-setup-step"><p className="budgy-eyebrow">Your household this month</p><h1>Here’s the plan you’re joining.</h1><div className="budgy-orientation-metrics"><span>Monthly income<b>{formatMoney(establishedSummary.income)}</b></span><span>Planned<b>{formatMoney(establishedSummary.spending)}</b></span><span>Savings target<b>{formatMoney(establishedSummary.savings)}</b></span></div><p>These are the household’s real shared figures. You do not need to recreate them.</p></section>}
      {step===2&&<section className="budgy-setup-step"><p className="budgy-eyebrow">The essentials</p><h1>Plan together. Record what happens.</h1><div className="budgy-concept-grid"><span><b>Budget</b>What the money is for</span><span><b>Money</b>Where it lives</span><span><b>+</b>Record money moving</span><span><b>Reports</b>Understand the month</span></div><div className="budgy-onboarding-nav-demo"><span>⌂<small>Home</small></span><span>▤<small>Budget</small></span><span className="is-add">+</span><span>▣<small>Money</small></span><span>•••<small>More</small></span></div></section>}
      {step===3&&<section className="budgy-setup-step"><p className="budgy-eyebrow">Ready</p><h1>You’re ready.</h1><p>Transactions are shared with household members. Use + whenever money moves, then Budgy will show how the real month compares with the plan.</p></section>}
    </>:<>
      {step===0&&<section className="budgy-setup-step"><p className="budgy-eyebrow">Household</p><h1>Who are you managing money with?</h1><p>Your household is the shared money space in Budgy. People in it can plan together and see the same shared financial picture.</p><div className="budgy-choice-grid">{([["solo","Just me"],["partner","Me + my partner"],["household","My household"]]as const).map(([value,label])=><button key={value} type="button" className={draft.householdMode===value?"is-selected":""} onClick={()=>setDraft({...draft,householdMode:value})}><b>{label}</b><span>{value==="solo"?"A private plan for now":value==="partner"?"Plan together when they join":"A shared space for your household"}</span></button>)}</div><label className="budgy-field"><span>What should we call your household?</span><input value={draft.householdName} onChange={(event)=>setDraft({...draft,householdName:event.target.value})} placeholder={`${displayName}'s household`}/></label>{draft.householdMode==="partner"&&<p className="budgy-setup-note">You can invite your partner from Household settings after setup. They’ll join as themselves—Budgy never creates a fake member.</p>}</section>}
      {step===1&&<section className="budgy-setup-step"><p className="budgy-eyebrow">Income</p><h1>What money comes in each month?</h1><p>Start with regular monthly income. You can change this anytime.</p><div className="budgy-setup-list">{draft.income.map((source,index)=><article key={source.id}><div className="budgy-setup-row-heading"><b>{index===0?"Your income":"Household income"}</b>{draft.income.length>1&&<button type="button" onClick={()=>setDraft({...draft,income:draft.income.filter((row)=>row.id!==source.id)})}>Remove</button>}</div><div className="budgy-form-grid"><label className="budgy-field"><span>Income type</span><select value={source.category??data.incomeCategories[0]} onChange={(event)=>updateIncome(source.id,{category:event.target.value})}>{data.incomeCategories.map((category)=><option key={category}>{category}</option>)}</select></label><label className="budgy-field"><span>Source</span><input value={source.name} onChange={(event)=>updateIncome(source.id,{name:event.target.value})} placeholder={index===0?"Employer or client":"Partner's salary"}/></label><MoneyInput label="Monthly amount" value={source.amount} onChange={(amount)=>updateIncome(source.id,{amount})}/></div></article>)}</div><button className="budgy-button budgy-button--quiet" type="button" onClick={addIncome}>+ Add another income</button><PlanSummary income={draft.income} outgoings={draft.outgoings} savings={draft.savings}/></section>}
      {step===2&&<section className="budgy-setup-step"><p className="budgy-eyebrow">Outgoings</p><h1>What do you normally spend money on?</h1><p>Choose the things that are part of a normal month, then add the expected amount.</p><div className="budgy-outgoing-groups">{Array.from(new Set(outgoingOptions.map((option)=>option.section))).map((section)=><fieldset key={section}><legend>{section}</legend>{outgoingOptions.filter((option)=>option.section===section).map((option)=>{const item=selected(option);return <div className={item?"is-selected":""} key={option.name}><label><input type="checkbox" checked={!!item} onChange={()=>toggleOutgoing(option)}/><span>{option.name}</span></label>{item&&<MoneyInput value={item.amount} onChange={(amount)=>setDraft((current)=>({...current,outgoings:current.outgoings.map((row)=>row.id===item.id?{...row,amount}:row)}))}/>}</div>;})}</fieldset>)}</div>{unmatched.length>0&&<div className="budgy-existing-plan"><b>Already in your plan</b><p>{unmatched.map((item)=>`${item.name} · ${formatMoney(item.amount)}`).join("  •  ")}</p></div>}<PlanSummary income={draft.income} outgoings={draft.outgoings} savings={draft.savings}/></section>}
      {step===3&&<section className="budgy-setup-step"><p className="budgy-eyebrow">Savings</p><h1>What do you want to put aside?</h1><p>Set a monthly savings target. This is the plan; later, transfers show what you actually saved and where it lives.</p><div className="budgy-savings-question"><MoneyInput label="Monthly savings target" value={draft.savings} onChange={(savings)=>setDraft({...draft,savings})}/><button className="budgy-button budgy-button--quiet" type="button" onClick={()=>setDraft({...draft,savings:0})}>Skip for now</button></div><PlanSummary income={draft.income} outgoings={draft.outgoings} savings={draft.savings}/></section>}
      {step===4&&<section className="budgy-setup-step"><p className="budgy-eyebrow">Your first month is ready</p><h1>You’ve built your monthly plan.</h1><div className="budgy-ready-summary"><span>Coming in<b>{formatMoney(summary.income)}</b></span><span>Monthly commitments<b>{formatMoney(summary.spending)}</b></span><span>Saving<b>{formatMoney(summary.savings)}</b></span><span className={summary.remaining<0?"is-negative":""}>Left to plan<b>{formatMoney(summary.remaining)}</b></span></div><p>Budgy will now help you compare this plan with what actually happens during the month.</p><div className="budgy-plan-actual"><div><b>Groceries</b><span>Planned <strong>£350</strong></span></div><span className="budgy-plan-actual-arrow">→</span><div><b>Tesco £42.50</b><span>£307.50 remaining</span></div></div><p><b>Your budget is the plan. Transactions are what actually happened.</b> Use + whenever money moves.</p><div className="budgy-onboarding-nav-demo"><span>⌂<small>Home</small></span><span>▤<small>Budget</small></span><span className="is-add">+</span><span>▣<small>Money</small></span><span>•••<small>More</small></span></div><div className="budgy-money-explainer"><div><b>Budget</b><span>What money is for</span></div><div><b>Money</b><span>Where it lives</span></div></div>{!data.accounts.length&&!accountOpen&&<div className="budgy-account-prompt"><div><b>Want to add an account now?</b><span>This is optional—you can finish without one.</span></div><button className="budgy-button budgy-button--quiet" type="button" onClick={()=>{setAccountError("");setAccountOpen(true);}}>Add account</button></div>}{accountOpen&&<div className="budgy-setup-account"><AccountForm onCancel={()=>setAccountOpen(false)} onSave={(account:FinancialAccount)=>{setAccountError("");void saveData((current)=>({...current,accounts:[...current.accounts.filter((entry)=>entry.id!==account.id),account]})).then(()=>setAccountOpen(false)).catch((reason)=>setAccountError(reason instanceof Error?reason.message:"The account could not be saved."));}}/>{accountError&&<p className="budgy-auth-message" role="alert">{accountError}</p>}</div>}</section>}
    </>}
  </div>{error&&<p className="budgy-auth-message budgy-setup-error" role="alert">{error}</p>}<footer>{step===0?<button className="budgy-button budgy-button--quiet" type="button" onClick={onSkip}>{orientation?"Finish later":"Finish later"}</button>:<button className="budgy-button budgy-button--quiet" type="button" onClick={()=>setStep((value)=>value-1)}>Back</button>}<button className="budgy-button budgy-button--primary" type="button" disabled={busy||accountOpen} onClick={()=>void next()}>{busy?"Saving…":(orientation&&step===3)||(!orientation&&step===4)?"See my month":"Continue"}</button></footer></section></div>;
};
export default GuidedOnboarding;
