import React,{useEffect,useRef,useState}from"react";
import{recordOnboardingEvent}from"../application/onboardingState";

const StepOne:React.FC<{name:string}>=({name})=><><p className="budgy-eyebrow">Welcome</p><h1>{name?`Welcome to Budgy, ${name}`:"Welcome to Budgy"}</h1><p className="budgy-onboarding-lede">One place for your household to plan, spend, save and understand your money together.</p><div className="budgy-onboarding-flow" aria-label="Income flows into a budget, spending and understanding"><span>Income</span><i>↓</i><span>Budget</span><i>↓</i><span>Spend</span><i>↓</i><span>Understand</span></div><p>Budgy connects what you plan to spend with what you actually spend.</p></>;
const StepTwo=()=> <><p className="budgy-eyebrow">Budget · What is this money for?</p><h1>Start with your monthly plan</h1><p>Budget is where you decide how household income should be used.</p><div className="budgy-onboarding-budget-preview"><header><span>Groceries</span><b>£350 planned</b></header><div><span>Spent <b>£80</b></span><span>Remaining <b>£270</b></span></div><i><span/></i></div><div className="budgy-onboarding-mini-list"><span>Transport <b>£673</b></span><span>Personal <b>£500</b></span><span>Savings <b>£2,500</b></span></div></>;
const StepThree=()=> <><p className="budgy-eyebrow">Money · Where is the money?</p><h1>Know where your money lives</h1><p><b>Budget</b> is what the money is for. <b>Money</b> is where the money actually is.</p><div className="budgy-onboarding-compare"><article><small>Budget</small><h3>Groceries</h3><strong>£350 planned</strong></article><article><small>Money</small><h3>Current account</h3><strong>£1,420</strong><hr/><h3>Credit card</h3><strong>£480 owed</strong></article></div><p>Track current accounts, savings, cash and credit cards without accounting jargon.</p></>;
const StepFour=()=> <><p className="budgy-eyebrow">Transaction · What actually happened?</p><h1>Record money in seconds</h1><p>Tap + whenever money moves.</p><div className="budgy-onboarding-nav-demo"><span>⌂<small>Home</small></span><span>▤<small>Budget</small></span><span className="is-add">+</span><span>▣<small>Money</small></span><span>•••<small>More</small></span></div><div className="budgy-onboarding-transaction"><div><b>Tesco</b><strong>£42.50</strong></div><small>Groceries · Paid from Amex</small><small>Counts against Household → Groceries</small><footer><span>£42.50 spent</span><b>£307.50 remaining</b></footer></div><div className="budgy-onboarding-action-key"><span><b>Transaction</b> Something you bought</span><span><b>Income</b> Money coming in</span><span><b>Transfer</b> Move between accounts</span><span><b>Card payment</b> Pay down a card</span></div></>;
const StepFive=()=> <><p className="budgy-eyebrow">Report · What happened this month?</p><h1>See where the month went</h1><p>Home and Reports turn recorded activity into a clear monthly picture.</p><div className="budgy-onboarding-report"><header><span>Example · September</span><small>Illustrative figures</small></header><div><span>Income <b>£7,500</b></span><span>Spent <b>£4,120</b></span><span>Saved <b>£2,500</b></span><span>Left <b>£880</b></span></div><footer><span>Groceries <b>£287 / £350</b></span><i><em style={{width:"82%"}}/></i><span>Transport <b>£510 / £673</b></span><i><em style={{width:"76%"}}/></i></footer></div><p>Use More for reports, transactions, goals, planning and household settings.</p></>;

const steps=[StepOne,StepTwo,StepThree,StepFour,StepFive];
const OnboardingWalkthrough:React.FC<{displayName:string;replaying:boolean;busy:boolean;error:string;onSkip:()=>void;onFinish:()=>void}>=({displayName,replaying,busy,error,onSkip,onFinish})=>{
  const[step,setStep]=useState(0);const headingRef=useRef<HTMLDivElement>(null);const Step=steps[step];
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous;};},[]);
  useEffect(()=>{recordOnboardingEvent(step===0?"onboarding_started":"onboarding_step_viewed",step+1);headingRef.current?.focus();},[step]);
  useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")onSkip();};window.addEventListener("keydown",escape);return()=>window.removeEventListener("keydown",escape);},[onSkip]);
  return <div className="budgy-onboarding-layer" role="dialog" aria-modal="true" aria-label={`Budgy walkthrough, step ${step+1} of ${steps.length}`}><section className="budgy-onboarding-walkthrough"><header><div className="budgy-brand"><span className="budgy-brand-mark">B</span><span className="budgy-brand-name">budgy</span></div><span>Step {step+1} of {steps.length}</span></header><div className="budgy-onboarding-progress" aria-hidden="true">{steps.map((_,index)=><i key={index} className={index<=step?"is-active":""}/>)}</div><div className="budgy-onboarding-content" ref={headingRef} tabIndex={-1}><Step name={displayName}/></div>{error&&<p className="budgy-auth-message" role="alert">{error}</p>}<footer>{step===0?<button type="button" className="budgy-button budgy-button--quiet" onClick={onSkip}>{replaying?"Close walkthrough":"Skip for now"}</button>:<button type="button" className="budgy-button budgy-button--quiet" onClick={()=>setStep((current)=>current-1)}>Back</button>}<button type="button" className="budgy-button budgy-button--primary" disabled={busy} onClick={()=>step===steps.length-1?onFinish():setStep((current)=>current+1)}>{busy?"Saving…":step===0?"Show me around":step===steps.length-1?"Get started":"Next"}</button></footer></section></div>;
};
export default OnboardingWalkthrough;
