import { SupabaseClient } from "@supabase/supabase-js";
import { Activity, ChildPreference, Expense, Household, HouseholdInvitation, Medicine, NestData, ShoppingItem, Supply, User, UserPreferences } from "../domain/types";

interface MemberRow { id: string; household_id: string; user_id: string; role: "owner" | "parent" | "caregiver"; relationship_label: string | null; joined_at: string }
interface HouseholdRow { id: string; name: string; created_by: string; created_at: string }
interface ProfileRow { id: string; email: string; display_name: string; avatar_url: string | null; onboarding_completed: boolean }
interface ChildRow { id: string; household_id: string; name: string; date_of_birth: string; photo_url: string | null; created_at: string }
interface PreferenceRow { id: string; child_id: string; category: ChildPreference["category"]; label: string }
interface ActivityRow { id: string; household_id: string; child_id: string; type: Activity["type"]; occurred_at: string; ended_at: string | null; created_by: string; metadata: Activity["metadata"]; created_at: string; updated_at: string }
interface SupplyRow { id: string; household_id: string; child_id: string | null; name: string; category: Supply["category"]; quantity: number; unit: string; estimated_daily_usage: number | null; low_stock_threshold: number; active: boolean; created_at: string; updated_at: string }
interface MedicineRow { id: string; child_id: string; name: string; default_dose: number; unit: string; schedule: Medicine["schedule"] | null; active: boolean }
interface ShoppingRow { id: string; household_id: string; child_id: string | null; supply_id: string | null; name: string; reason: string | null; completed: boolean; created_at: string; completed_at: string | null }
interface ExpenseRow { id: string; household_id: string; child_id: string; amount_pence: number; category: Expense["category"]; description: string; occurred_at: string }
interface UserPreferenceRow { user_id: string; selected_household_id: string | null; selected_child_id: string | null; preferred_quick_actions: string[]; dismissed_prompts: string[]; night_care_enabled: boolean; preferred_units: UserPreferences["preferredUnits"]; handover_viewed_at: string | null }

const rows = <T>(value: unknown): T[] => (value ?? []) as T[];
const one = <T>(value: unknown): T | null => (value ?? null) as T | null;
const throwIf = (error: { message: string } | null): void => { if (error) throw new Error(error.message); };

export class SupabaseNestRepository {
  private saveQueue: Promise<void> = Promise.resolve();
  constructor(private client: SupabaseClient, private userId: string) {}

  async profile(): Promise<{ profile: ProfileRow | null; hasHousehold: boolean }> {
    const [profileResult, membershipResult] = await Promise.all([this.client.from("nest_profiles").select("*").eq("id", this.userId).maybeSingle(), this.client.from("nest_household_members").select("id").eq("user_id", this.userId).limit(1)]);
    throwIf(profileResult.error); throwIf(membershipResult.error); return { profile: one<ProfileRow>(profileResult.data), hasHousehold: rows(membershipResult.data).length > 0 };
  }

  async load(): Promise<NestData> {
    const [membershipResult, preferenceResult] = await Promise.all([this.client.from("nest_household_members").select("*").eq("user_id", this.userId), this.client.from("nest_user_preferences").select("*").eq("user_id", this.userId).maybeSingle()]);
    throwIf(membershipResult.error); throwIf(preferenceResult.error); const ownMemberships = rows<MemberRow>(membershipResult.data); if (!ownMemberships.length) throw new Error("ONBOARDING_REQUIRED");
    const userPreference = one<UserPreferenceRow>(preferenceResult.data); const householdIds = ownMemberships.map((item) => item.household_id); const selectedHouseholdId = userPreference?.selected_household_id && householdIds.includes(userPreference.selected_household_id) ? userPreference.selected_household_id : householdIds[0];
    const [householdsResult, membersResult, childrenResult, activitiesResult, suppliesResult, medicinesResult, shoppingResult, expensesResult, preferencesResult, invitationsResult] = await Promise.all([
      this.client.from("nest_households").select("*").in("id", householdIds), this.client.from("nest_household_members").select("*").in("household_id", householdIds),
      this.client.from("nest_children").select("*").eq("household_id", selectedHouseholdId), this.client.from("nest_activities").select("*").eq("household_id", selectedHouseholdId).order("occurred_at", { ascending: false }),
      this.client.from("nest_supplies").select("*").eq("household_id", selectedHouseholdId), this.client.from("nest_medicines").select("*").eq("household_id", selectedHouseholdId),
      this.client.from("nest_shopping_items").select("*").eq("household_id", selectedHouseholdId), this.client.from("nest_expenses").select("*").eq("household_id", selectedHouseholdId),
      this.client.from("nest_child_preferences").select("*").eq("household_id", selectedHouseholdId), this.client.from("nest_household_invitations").select("*").eq("household_id", selectedHouseholdId),
    ]);
    [householdsResult,membersResult,childrenResult,activitiesResult,suppliesResult,medicinesResult,shoppingResult,expensesResult,preferencesResult,invitationsResult].forEach((result) => throwIf(result.error));
    const memberRows = rows<MemberRow>(membersResult.data); const userIds = Array.from(new Set(memberRows.map((item) => item.user_id))); const profilesResult = await this.client.from("nest_profiles").select("*").in("id", userIds); throwIf(profilesResult.error);
    const profiles = rows<ProfileRow>(profilesResult.data); const users: User[] = profiles.map((item) => ({ id: item.id, email: item.email, displayName: item.display_name || item.email, avatarUrl: item.avatar_url ?? undefined }));
    const householdRows = rows<HouseholdRow>(householdsResult.data); const households: Household[] = householdRows.map((item) => ({ id: item.id, name: item.name, createdBy: item.created_by, createdAt: item.created_at, members: memberRows.filter((member) => member.household_id === item.id).map((member) => ({ id: member.id, userId: member.user_id, role: member.role, relationshipLabel: member.relationship_label ?? undefined, joinedAt: member.joined_at })) }));
    const household = households.find((item) => item.id === selectedHouseholdId) ?? households[0]; const prefRows = rows<PreferenceRow>(preferencesResult.data);
    const children = rows<ChildRow>(childrenResult.data).map((item) => ({ id: item.id, householdId: item.household_id, name: item.name, birthday: item.date_of_birth, initials: item.name.slice(0, 1).toUpperCase(), preferences: prefRows.filter((pref) => pref.child_id === item.id).map((pref) => ({ id: pref.id, childId: pref.child_id, category: pref.category, label: pref.label })) }));
    const activities = rows<ActivityRow>(activitiesResult.data).map((item) => ({ id: item.id, householdId: item.household_id, childId: item.child_id, type: item.type, occurredAt: item.occurred_at, endedAt: item.ended_at ?? undefined, createdBy: item.created_by, metadata: item.metadata, createdAt: item.created_at, updatedAt: item.updated_at }) as Activity);
    const supplies = rows<SupplyRow>(suppliesResult.data).map((item) => ({ id: item.id, householdId: item.household_id, childId: item.child_id ?? undefined, name: item.name, category: item.category, quantity: Number(item.quantity), unit: item.unit, estimatedDailyUsage: item.estimated_daily_usage === null ? undefined : Number(item.estimated_daily_usage), lowStockThreshold: Number(item.low_stock_threshold), active: item.active, createdAt: item.created_at, updatedAt: item.updated_at }));
    const medicines = rows<MedicineRow>(medicinesResult.data).map((item) => ({ id: item.id, childId: item.child_id, name: item.name, defaultDose: Number(item.default_dose), unit: item.unit, schedule: item.schedule ?? undefined, active: item.active }));
    const shoppingItems: ShoppingItem[] = rows<ShoppingRow>(shoppingResult.data).map((item) => ({ id: item.id, householdId: item.household_id, childId: item.child_id ?? undefined, supplyId: item.supply_id ?? undefined, name: item.name, reason: item.reason ?? undefined, completed: item.completed, createdAt: item.created_at, completedAt: item.completed_at ?? undefined }));
    const expenses: Expense[] = rows<ExpenseRow>(expensesResult.data).map((item) => ({ id: item.id, householdId: item.household_id, childId: item.child_id, amountPence: item.amount_pence, category: item.category, description: item.description, occurredAt: item.occurred_at }));
    const invitations: HouseholdInvitation[] = rows<{ id: string; household_id: string; email: string; role: HouseholdInvitation["role"]; expires_at: string; accepted_at: string | null; invited_by: string }>(invitationsResult.data).map((item) => ({ id: item.id, householdId: item.household_id, email: item.email, role: item.role, expiresAt: item.expires_at, acceptedAt: item.accepted_at ?? undefined, invitedBy: item.invited_by }));
    return { version: 3, users, household, households, invitations, userPreferences: { userId: this.userId, selectedHouseholdId, selectedChildId: userPreference?.selected_child_id ?? children[0]?.id, preferredQuickActions: userPreference?.preferred_quick_actions ?? [], dismissedPrompts: userPreference?.dismissed_prompts ?? [], nightCareEnabled: userPreference?.night_care_enabled ?? false, preferredUnits: userPreference?.preferred_units ?? { temperature: "celsius", volume: "ml" } }, children, activities, supplies, shoppingItems, medicines, expenses, milestones: [], handoverViewedAt: userPreference?.handover_viewed_at ?? undefined };
  }

  save(data: NestData): Promise<void> { this.saveQueue = this.saveQueue.then(() => this.persist(data)); return this.saveQueue; }
  private async persist(data: NestData): Promise<void> {
    const childRows = data.children.map((item) => ({ id:item.id,household_id:item.householdId,name:item.name,date_of_birth:item.birthday }));
    const activityRows = data.activities.map((item) => ({ id:item.id,household_id:item.householdId,child_id:item.childId,type:item.type,occurred_at:item.occurredAt,ended_at:item.endedAt??null,created_by:item.createdBy,metadata:item.metadata,created_at:item.createdAt,updated_at:item.updatedAt }));
    const medicineLogRows = data.activities.filter((item): item is Extract<Activity,{type:"medicine"}> => item.type === "medicine").map((item) => ({ id:item.id,household_id:item.householdId,child_id:item.childId,medicine_id:item.metadata.medicineId,dose:item.metadata.dose,unit:item.metadata.unit,occurred_at:item.occurredAt,created_by:item.createdBy }));
    const supplyRows = data.supplies.map((item) => ({ id:item.id,household_id:item.householdId,child_id:item.childId??null,name:item.name,category:item.category,quantity:item.quantity,unit:item.unit,estimated_daily_usage:item.estimatedDailyUsage??null,low_stock_threshold:item.lowStockThreshold,active:item.active,created_at:item.createdAt,updated_at:item.updatedAt }));
    const shoppingRows = data.shoppingItems.map((item) => ({ id:item.id,household_id:item.householdId,child_id:item.childId??null,supply_id:item.supplyId??null,name:item.name,reason:item.reason??null,completed:item.completed,created_by:this.userId,created_at:item.createdAt,completed_at:item.completedAt??null }));
    const expenseRows = data.expenses.map((item) => ({ id:item.id,household_id:item.householdId,child_id:item.childId,amount_pence:item.amountPence,category:item.category,description:item.description,occurred_at:item.occurredAt,created_by:this.userId }));
    const preferenceRows = data.children.flatMap((child) => child.preferences.map((item) => ({ id:item.id,household_id:data.household.id,child_id:item.childId,category:item.category,label:item.label,created_by:this.userId })));
    const upsert = async (table: string, values: Array<Record<string, unknown>>): Promise<void> => { if (!values.length) return; const result = await this.client.from(table).upsert(values); throwIf(result.error); };
    await upsert("nest_children",childRows); await upsert("nest_activities",activityRows); await upsert("nest_medicine_logs",medicineLogRows); await upsert("nest_supplies",supplyRows); await upsert("nest_shopping_items",shoppingRows); await upsert("nest_expenses",expenseRows); await upsert("nest_child_preferences",preferenceRows);
    for (const [table, ids] of [["nest_activities",data.activities.map((item)=>item.id)],["nest_shopping_items",data.shoppingItems.map((item)=>item.id)],["nest_child_preferences",preferenceRows.map((item)=>item.id)]] as const) { const existing = await this.client.from(table).select("id").eq("household_id",data.household.id); throwIf(existing.error); const removed = rows<{id:string}>(existing.data).map((item)=>item.id).filter((id)=>!ids.includes(id)); if (removed.length) { const deletion = await this.client.from(table).delete().in("id",removed); throwIf(deletion.error); } }
    const prefResult = await this.client.from("nest_user_preferences").upsert({ user_id:this.userId,selected_household_id:data.household.id,selected_child_id:data.userPreferences.selectedChildId??data.children[0]?.id,preferred_quick_actions:data.userPreferences.preferredQuickActions,dismissed_prompts:data.userPreferences.dismissedPrompts,night_care_enabled:data.userPreferences.nightCareEnabled,preferred_units:data.userPreferences.preferredUnits,handover_viewed_at:data.handoverViewedAt??null }); throwIf(prefResult.error);
  }
  async createHousehold(input: { householdName: string; childName: string; birthDate: string; feeding: string[]; relationship: string }): Promise<void> { const result = await this.client.rpc("nest_create_household", { household_name: input.householdName, child_name: input.childName, child_birth_date: input.birthDate, feeding: input.feeding, relationship: input.relationship }); throwIf(result.error); }
  async updateProfile(displayName: string, relationship: string): Promise<void> { const result = await this.client.from("nest_profiles").update({ display_name: displayName.trim(), relationship_label: relationship }).eq("id", this.userId); throwIf(result.error); }
  async invite(householdId: string, email: string, role: "parent" | "caregiver" = "parent"): Promise<string> { const token = crypto.randomUUID()+crypto.randomUUID(); const bytes = new TextEncoder().encode(token); const digest = await crypto.subtle.digest("SHA-256", bytes); const hash = Array.from(new Uint8Array(digest)).map((value) => value.toString(16).padStart(2,"0")).join(""); const result = await this.client.rpc("nest_create_invitation", { target_household: householdId, invite_email: email.trim().toLowerCase(), invite_role: role, invite_hash: hash }); throwIf(result.error); return token; }
  async acceptInvitation(token: string): Promise<void> { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(token)); const hash = Array.from(new Uint8Array(digest)).map((value) => value.toString(16).padStart(2,"0")).join(""); const result = await this.client.rpc("nest_accept_invitation", { invite_hash: hash }); throwIf(result.error); }
  async clear(): Promise<void> { /* Server data is never cleared as a side effect of signing out. */ }
}
