export interface ProfileRow { id: string; display_name: string; email: string; avatar_url: string | null; created_at: string; updated_at: string; }
export interface HouseholdRow { id: string; name: string; created_by: string; created_at: string; updated_at: string; }
export interface HouseholdMemberRow { household_id: string; user_id: string; role: "owner" | "member"; joined_at: string; profiles?: Pick<ProfileRow, "display_name"> | null; }
export interface HouseholdInviteRow { id: string; household_id: string; email: string; role: "owner" | "member"; expires_at: string; accepted_at: string | null; created_at: string; }
export interface BudgetMonthRow { id: string; household_id: string; year: number; month: number; savings_target_pence: number; status: "open" | "closed"; created_at: string; updated_at: string; }
export interface CategoryRow { id: string; household_id: string; name: string; icon_key: string | null; sort_order: number; created_at: string; }
export interface IncomeSourceRow { id: string; household_id: string; budget_month_id: string; name: string; owner_user_id: string | null; owner_label: string | null; amount_pence: number; recurring: boolean; created_at: string; updated_at: string; }
export interface BudgetItemRow { id: string; household_id: string; budget_month_id: string; category_id: string; name: string; owner_user_id: string | null; owner_label: string | null; planned_amount_pence: number; recurring: boolean; track_actuals: boolean; created_at: string; updated_at: string; }
export interface TransactionRow { id: string; household_id: string; budget_month_id: string | null; category_id: string | null; type: "income" | "expense" | "refund" | "transfer" | "credit_card_payment"; amount_pence: number; description: string; owner_user_id: string | null; owner_label: string | null; transaction_date: string; note: string | null; created_by: string; account_id: string | null; destination_account_id: string | null; budget_item_id: string | null; created_at: string; updated_at: string; }
export interface FinancialAccountRow { id: string; household_id: string; owner_user_id: string | null; name: string; type: "current_account" | "savings_account" | "credit_card" | "cash" | "other"; currency: string; opening_balance_pence: number; credit_limit_pence: number | null; statement_balance_pence: number | null; payment_due_date: string | null; is_active: boolean; created_at: string; updated_at: string; }
export interface SavingsGoalRow { id: string; household_id: string; name: string; icon_key: string | null; target_amount_pence: number; current_amount_pence: number; monthly_contribution_pence: number; target_date: string | null; description: string | null; created_at: string; updated_at: string; }
export interface ScenarioRow { id: string; household_id: string; name: string; base_budget_month_id: string | null; created_by: string; created_at: string; updated_at: string; }
export interface ScenarioChangeRow { id: string; scenario_id: string; change_type: string; entity_type: string; entity_id: string | null; payload: unknown; created_at: string; }
export interface ActivityEventRow { id: string; household_id: string; actor_user_id: string | null; event_type: string; entity_type: string; entity_id: string | null; metadata: Record<string, unknown>; created_at: string; profiles?: Pick<ProfileRow, "display_name"> | null; }
