import React from "react";
import {Link,useParams} from "react-router-dom";
import {LuArrowLeft,LuBadgeCheck,LuDumbbell,LuHistory,LuLightbulb,LuTrendingUp} from "react-icons/lu";
import {exerciseById} from "../data/exercises";
import ExerciseAnimation from "../components/workout/ExerciseAnimation";
import {useVela} from "../store/VelaStore";

const label=(value:string)=>value.replace(/-/g," ");
const ExerciseDetail:React.FC=()=>{
 const{id=""}=useParams();const exercise=exerciseById(id);const{data}=useVela();const record=data.records.find(item=>item.exerciseId===exercise.id);const alternatives=exercise.substitutions.map(exerciseById).filter(item=>item.id!==exercise.id).slice(0,4);
 return <div className="vela-page vela-exercise-detail"><Link className="vela-back-link" to="/vela/train"><LuArrowLeft/> Exercise library</Link><section className="vela-detail-hero"><ExerciseAnimation exerciseId={exercise.id}/><div><p className="vela-eyebrow">{label(exercise.movementPattern)} · {exercise.exerciseType}</p><h1>{exercise.name}</h1><div className="vela-detail-tags"><span>{label(exercise.category)}</span><span>{exercise.equipment.map(label).join(" · ")}</span><span>{exercise.difficulty}</span></div><p>{exercise.description}</p></div></section>
 <div className="vela-detail-grid"><main><section><h2>How to perform it</h2><ol>{exercise.instructions.map((step,index)=><li key={`${index}-${step}`}><span>{index+1}</span><p>{step}</p></li>)}</ol></section>{exercise.cues.length>0&&<section><h2><LuLightbulb/> Technique cues</h2><div className="vela-cue-grid">{exercise.cues.map(cue=><p key={cue}><LuBadgeCheck/>{cue}</p>)}</div></section>}{alternatives.length>0&&<section><h2>Similar movements</h2><div className="vela-library-grid">{alternatives.map(item=><Link key={item.id} to={`/vela/exercise/${item.id}`}><span>{item.name[0]}</span><div><strong>{item.name}</strong><small>{label(item.movementPattern)} · {item.equipment.map(label).join(", ")}</small></div></Link>)}</div></section>}<p className="vela-library-attribution"><a href="https://repdb.co" target="_blank" rel="noreferrer">Exercise data by RepDB (repdb.co)</a></p></main>
 <aside><section><p className="vela-eyebrow"><LuHistory/> Previous performance</p><strong>{record?`${record.value}${record.kind==="reps"?" reps":"kg"}`:"No logged sets yet"}</strong><span>{record?new Date(`${record.date}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"}):"Complete this movement to start tracking"}</span></section><section><p className="vela-eyebrow"><LuTrendingUp/> Training profile</p><strong>{exercise.mechanic} · {exercise.forceType}</strong><span>{exercise.goals.map(label).join(" · ")}</span></section><section><p className="vela-eyebrow"><LuDumbbell/> Muscles</p>{[...exercise.primaryMuscles,...exercise.secondaryMuscles].slice(0,7).map((muscle,index)=><div className="vela-muscle-row" key={muscle}><span>{label(muscle)}</span><i><em style={{width:index<exercise.primaryMuscles.length?"92%":"55%"}}/></i></div>)}</section></aside></div></div>;
};
export default ExerciseDetail;
