import React,{useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {LuArrowRight,LuBookOpen,LuCalendarDays,LuChevronRight,LuClock3,LuDumbbell,LuHistory} from "react-icons/lu";
import {exercises,exerciseById} from "../data/exercises";
import {searchExercises} from "../domain/exerciseSearch";
import {Equipment,Experience,MovementPattern,MuscleGroup} from "../domain/types";
import {useVela} from "../store/VelaStore";

const equipmentOptions:Equipment[]=["bodyweight","dumbbell","barbell","cable","machine","band","kettlebell","pull-up-bar","cardio"];
const muscleOptions:MuscleGroup[]=["chest","back","shoulders","biceps","triceps","quads","hamstrings","glutes","calves","core","full-body","cardio","mobility"];
const movementOptions:MovementPattern[]=["push-horizontal","push-vertical","pull-horizontal","pull-vertical","squat","hinge","lunge","carry","isolation","core","cardio","mobility"];

const Train:React.FC=()=>{
 const{data,today}=useVela();const[query,setQuery]=useState("");const[equipment,setEquipment]=useState<Equipment|undefined>();const[difficulty,setDifficulty]=useState<Experience|undefined>();const[muscle,setMuscle]=useState<MuscleGroup|undefined>();const[movement,setMovement]=useState<MovementPattern|undefined>();const[limit,setLimit]=useState(36);
 const completed=data.workouts.filter(item=>item.status==="complete");
 const results=useMemo(()=>searchExercises(exercises,query,{equipment,difficulty,muscleGroup:muscle,movementPattern:movement}),[query,equipment,difficulty,muscle,movement]);
 return <div className="vela-page"><header className="vela-page-head"><div><p className="vela-eyebrow">Your training</p><h1>Build steadily. Stay flexible.</h1><p>A plan that adapts around your goals, experience and available equipment.</p></div><Link className="vela-button primary" to="/vela/onboarding">Edit program</Link></header>
 <section className="vela-program-hero"><div><p className="vela-eyebrow">Current program · Week 4 of 8</p><h2>Upper / Lower Momentum</h2><p>Built for fat loss with strength retention. Main lifts progress through a controlled 8–12 rep range.</p><div><span><LuCalendarDays/>{data.profile.daysPerWeek} days / week</span><span><LuClock3/>~{data.profile.workoutMinutes} min</span><span><LuDumbbell/>{data.profile.location.replace(/-/g," ")}</span></div></div><div className="vela-program-score"><strong>86%</strong><span>plan consistency</span></div></section>
 <section className="vela-section"><header><div><p className="vela-eyebrow">This week</p><h2>Your schedule</h2></div><span>3 of 4 complete</span></header><div className="vela-week-plan">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day,index)=><article key={day} className={index===4?"today":index<4&&index!==2?"complete":index===2||index>5?"rest":""}><span>{day}</span><i>{index===4?"Today":index===2||index>5?"Rest":"✓"}</i><strong>{index===0?"Upper":index===1?"Lower":index===3?"Upper":index===4?"Lower":"Recover"}</strong></article>)}</div></section>
 <section className="vela-train-grid"><div><div className="vela-section-head-inline"><div><p className="vela-eyebrow">Up next</p><h2>{today.title}</h2></div><Link to={`/vela/workout/${today.id}`}>Open workout <LuArrowRight/></Link></div><div className="vela-preview-list">{today.exercises.slice(0,5).map((item,index)=><article key={item.id}><b>{String(index+1).padStart(2,"0")}</b><span><strong>{exerciseById(item.exerciseId).name}</strong><small>{item.sets.length} sets · {item.sets[0].targetReps[0]}–{item.sets[0].targetReps[1]} reps</small></span><LuChevronRight/></article>)}</div></div><aside><p className="vela-eyebrow"><LuHistory/> Recent sessions</p>{completed.slice(0,4).map(workout=><article key={workout.id}><span>{new Date(`${workout.date}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}</span><div><strong>{workout.title}</strong><small>{workout.exercises.length} exercises · {workout.estimatedMinutes} min</small></div></article>)}</aside></section>
 <section className="vela-section"><header><div><p className="vela-eyebrow"><LuBookOpen/> Exercise library</p><h2>Learn every movement</h2><span className="vela-library-summary">{results.length} of {exercises.length} exercises</span></div><input aria-label="Search exercises" value={query} onChange={event=>{setQuery(event.target.value);setLimit(36);}} placeholder="Search name, muscle, equipment…"/></header>
 <div className="vela-exercise-filters"><select aria-label="Filter by muscle group" value={muscle||""} onChange={event=>setMuscle((event.target.value||undefined) as MuscleGroup|undefined)}><option value="">All muscle groups</option>{muscleOptions.map(value=><option key={value} value={value}>{value.replace(/-/g," ")}</option>)}</select><select aria-label="Filter by equipment" value={equipment||""} onChange={event=>setEquipment((event.target.value||undefined) as Equipment|undefined)}><option value="">All equipment</option>{equipmentOptions.map(value=><option key={value} value={value}>{value.replace(/-/g," ")}</option>)}</select><select aria-label="Filter by difficulty" value={difficulty||""} onChange={event=>setDifficulty((event.target.value||undefined) as Experience|undefined)}><option value="">All levels</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select><select aria-label="Filter by movement" value={movement||""} onChange={event=>setMovement((event.target.value||undefined) as MovementPattern|undefined)}><option value="">All movements</option>{movementOptions.map(value=><option key={value} value={value}>{value.replace(/-/g," ")}</option>)}</select></div>
 <div className="vela-library-grid">{results.slice(0,limit).map(exercise=><Link key={exercise.id} to={`/vela/exercise/${exercise.id}`}>{exercise.media?<img className="vela-library-thumb" src={exercise.media.start} alt="" loading="lazy"/>:<span>{exercise.name.slice(0,1)}</span>}<div><strong>{exercise.name}</strong><small>{exercise.category.replace(/-/g," ")} · {exercise.equipment.join(", ")}</small></div><LuChevronRight/></Link>)}{results.length===0&&<p className="vela-empty-library">No exercises match those filters.</p>}</div>
 {limit<results.length&&<button className="vela-button quiet" onClick={()=>setLimit(value=>value+36)}>Show more exercises</button>}
 <p className="vela-library-attribution"><a href="https://repdb.co" target="_blank" rel="noreferrer">Exercise data by RepDB (repdb.co)</a></p></section></div>;
};
export default Train;
