import React,{useState} from "react";
import {Link,useNavigate} from "react-router-dom";
import {LuArrowRight,LuCheck,LuEye,LuEyeOff,LuShieldCheck} from "react-icons/lu";
import {useVelaAuth} from "./AuthProvider";
import {describeAuthError} from "./errors";

const Brand=()=> <Link className="vela-auth-brand" to="/vela"><i>v</i><strong>vela</strong></Link>;
const Password:React.FC<{value:string;onChange(value:string):void;autoComplete:string;label?:string}>=({value,onChange,autoComplete,label="Password"})=>{const[visible,setVisible]=useState(false);return <label className="vela-auth-field"><span>{label}</span><div><input required minLength={8} type={visible?"text":"password"} autoComplete={autoComplete} value={value} onChange={(event)=>onChange(event.target.value)}/><button type="button" onClick={()=>setVisible((current)=>!current)} aria-label={visible?"Hide password":"Show password"}>{visible?<LuEyeOff/>:<LuEye/>}</button></div></label>;};
const AuthFrame:React.FC<React.PropsWithChildren<{eyebrow:string;title:string;copy:string}>>=({eyebrow,title,copy,children})=><main className="vela-auth"><section className="vela-auth-story"><Brand/><div><p className="vela-eyebrow">Personal training, made personal</p><h1>Train for the life<br/>you actually live.</h1><p>Workouts, progression and nutrition that adapt around your goals, schedule and recovery.</p></div><ul><li><LuCheck/>A clear plan for today</li><li><LuCheck/>Progression based on your history</li><li><LuCheck/>Your data, private to your account</li></ul></section><section className="vela-auth-panel"><div className="vela-auth-card"><p className="vela-eyebrow">{eyebrow}</p><h2>{title}</h2><p>{copy}</p>{children}</div><p className="vela-auth-security"><LuShieldCheck/> Secure authentication powered by Supabase</p></section></main>;

export const Welcome:React.FC=()=> <main className="vela-welcome"><Brand/><div className="vela-welcome-orbit" aria-hidden="true"><i/><i/><i/></div><section><p className="vela-eyebrow">Adaptive fitness coaching</p><h1>Personal training<br/>that adapts to you.</h1><p>Know what to train, what weight to use and what to eat—without needing to become your own coach.</p><div><Link className="vela-auth-primary" to="/vela/sign-up">Get started <LuArrowRight/></Link><Link className="vela-auth-secondary" to="/vela/sign-in">I already have an account</Link></div></section><small>General fitness guidance, not medical advice.</small></main>;

export const SignIn:React.FC=()=>{const{signIn}=useVelaAuth();const navigate=useNavigate();const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");return <AuthFrame eyebrow="Welcome back" title="Continue your plan" copy="Sign in to restore your workouts, meals and progress."><form className="vela-auth-form" onSubmit={async(event)=>{event.preventDefault();setBusy(true);setMessage("");try{await signIn(email,password);navigate("/vela");}catch(error){setMessage(describeAuthError(error));}finally{setBusy(false);}}}><label className="vela-auth-field"><span>Email</span><input autoFocus required type="email" inputMode="email" autoComplete="email" value={email} onChange={(event)=>setEmail(event.target.value)}/></label><Password value={password} onChange={setPassword} autoComplete="current-password"/>{message&&<p className="vela-auth-message" role="alert">{message}</p>}<button className="vela-auth-primary" disabled={busy}>{busy?"Signing in…":"Sign in"}<LuArrowRight/></button></form><div className="vela-auth-links"><Link to="/vela/forgot-password">Forgot password?</Link><span>New to Vela? <Link to="/vela/sign-up">Create account</Link></span></div></AuthFrame>;};

export const SignUp:React.FC=()=>{const{signUp}=useVelaAuth();const navigate=useNavigate();const[firstName,setFirst]=useState("");const[lastName,setLast]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[complete,setComplete]=useState(false);if(complete)return <AuthFrame eyebrow="One more step" title="Check your email" copy="We sent a verification link. Confirm your email to continue into fitness onboarding."><div className="vela-auth-success"><span>✓</span><p>You can close this page after confirming, then return to sign in.</p></div><Link className="vela-auth-primary" to="/vela/sign-in">Go to sign in <LuArrowRight/></Link></AuthFrame>;return <AuthFrame eyebrow="Create your account" title="Your plan starts here" copy="Account details first. We’ll build your fitness profile next."><form className="vela-auth-form" onSubmit={async(event)=>{event.preventDefault();if(password.length<8){setMessage("Use at least 8 characters for your password.");return;}setBusy(true);setMessage("");try{const result=await signUp({firstName,lastName,email,password});if(result.needsVerification)setComplete(true);else navigate("/vela/onboarding");}catch(error){setMessage(describeAuthError(error));}finally{setBusy(false);}}}><div className="vela-auth-name-row"><label className="vela-auth-field"><span>First name</span><input autoFocus required autoComplete="given-name" value={firstName} onChange={(event)=>setFirst(event.target.value)}/></label><label className="vela-auth-field"><span>Last name <small>Optional</small></span><input autoComplete="family-name" value={lastName} onChange={(event)=>setLast(event.target.value)}/></label></div><label className="vela-auth-field"><span>Email</span><input required type="email" inputMode="email" autoComplete="email" value={email} onChange={(event)=>setEmail(event.target.value)}/></label><Password value={password} onChange={setPassword} autoComplete="new-password"/><p className={`vela-password-hint ${password.length>=8?"valid":""}`}><LuCheck/> At least 8 characters</p>{message&&<p className="vela-auth-message" role="alert">{message}</p>}<button className="vela-auth-primary" disabled={busy}>{busy?"Creating account…":"Create account"}<LuArrowRight/></button></form><div className="vela-auth-links"><span>Already have an account? <Link to="/vela/sign-in">Sign in</Link></span></div></AuthFrame>;};

export const ForgotPassword:React.FC=()=>{const{sendPasswordReset}=useVelaAuth();const[email,setEmail]=useState("");const[busy,setBusy]=useState(false);const[sent,setSent]=useState(false);const[message,setMessage]=useState("");return <AuthFrame eyebrow="Account recovery" title={sent?"Check your inbox":"Reset your password"} copy={sent?"If an account exists for that email, we’ve sent password reset instructions.":"Enter your email and we’ll send a secure reset link."}>{!sent?<form className="vela-auth-form" onSubmit={async(event)=>{event.preventDefault();setBusy(true);setMessage("");try{await sendPasswordReset(email);setSent(true);}catch(error){const friendly=describeAuthError(error);if(friendly.includes("reach the server"))setMessage(friendly);else setSent(true);}finally{setBusy(false);}}}><label className="vela-auth-field"><span>Email</span><input autoFocus required type="email" inputMode="email" autoComplete="email" value={email} onChange={(event)=>setEmail(event.target.value)}/></label>{message&&<p className="vela-auth-message">{message}</p>}<button className="vela-auth-primary" disabled={busy}>{busy?"Sending…":"Send reset link"}<LuArrowRight/></button></form>:<div className="vela-auth-success"><span>✓</span><p>For privacy, this message is the same whether or not an account exists.</p></div>}<div className="vela-auth-links"><Link to="/vela/sign-in">Back to sign in</Link></div></AuthFrame>;};

export const ResetPassword:React.FC=()=>{const{updatePassword}=useVelaAuth();const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[done,setDone]=useState(false);return <AuthFrame eyebrow="Choose a new password" title={done?"Password updated":"Secure your account"} copy={done?"Your new password is ready to use.":"Use at least 8 characters and something unique to Vela."}>{done?<Link className="vela-auth-primary" to="/vela">Continue to Vela <LuArrowRight/></Link>:<form className="vela-auth-form" onSubmit={async(event)=>{event.preventDefault();if(password!==confirm){setMessage("Those passwords don’t match.");return;}setBusy(true);setMessage("");try{await updatePassword(password);setDone(true);}catch(error){setMessage(describeAuthError(error,"We couldn’t update your password. Request a new reset link and try again."));}finally{setBusy(false);}}}><Password value={password} onChange={setPassword} autoComplete="new-password" label="New password"/><Password value={confirm} onChange={setConfirm} autoComplete="new-password" label="Confirm password"/>{message&&<p className="vela-auth-message">{message}</p>}<button className="vela-auth-primary" disabled={busy}>{busy?"Updating…":"Update password"}<LuArrowRight/></button></form>}</AuthFrame>;};
