import React,{createContext,useContext,useEffect,useMemo,useState} from "react";
import {Session,User} from "@supabase/supabase-js";
import {requireVelaSupabase} from "../infrastructure/supabase/client";

interface SignUpInput{firstName:string;lastName?:string;email:string;password:string}
interface AuthValue{session:Session|null;user:User|null;isLoading:boolean;isAuthenticated:boolean;isRecovery:boolean;signIn(email:string,password:string):Promise<void>;signUp(input:SignUpInput):Promise<{needsVerification:boolean}>;sendPasswordReset(email:string):Promise<void>;updatePassword(password:string):Promise<void>;signOut():Promise<void>;}
const Context=createContext<AuthValue|null>(null);
export const VelaAuthProvider:React.FC<React.PropsWithChildren>=({children})=>{const client=requireVelaSupabase();const[session,setSession]=useState<Session|null>(null);const[isLoading,setLoading]=useState(true);const[isRecovery,setRecovery]=useState(false);
 useEffect(()=>{let active=true;void client.auth.getSession().then(({data})=>{if(active){setSession(data.session);setLoading(false);}});const{data}=client.auth.onAuthStateChange((event,next)=>{setSession(next);setRecovery(event==="PASSWORD_RECOVERY");setLoading(false);});return()=>{active=false;data.subscription.unsubscribe();};},[client]);
 const value=useMemo<AuthValue>(()=>({session,user:session?.user??null,isLoading,isAuthenticated:Boolean(session),isRecovery,signIn:async(email,password)=>{const{error}=await client.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;},signUp:async(input)=>{const{data,error}=await client.auth.signUp({email:input.email.trim(),password:input.password,options:{emailRedirectTo:`${window.location.origin}/vela`,data:{first_name:input.firstName.trim(),last_name:input.lastName?.trim()??""}}});if(error)throw error;return{needsVerification:!data.session};},sendPasswordReset:async(email)=>{const{error}=await client.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/vela/reset-password`});if(error)throw error;},updatePassword:async(password)=>{const{error}=await client.auth.updateUser({password});if(error)throw error;setRecovery(false);},signOut:async()=>{const{error}=await client.auth.signOut();if(error)throw error;setSession(null);}}),[client,session,isLoading,isRecovery]);return <Context.Provider value={value}>{children}</Context.Provider>;};
export const useVelaAuth=()=>{const value=useContext(Context);if(!value)throw new Error("useVelaAuth must be used inside VelaAuthProvider");return value;};
