import React, { useState } from "react";
import { Link, Navigate, useLocation, useNavigate } from "react-router-dom";
import { productConfig } from "../config/product";
import { useNestAuth } from "./AuthProvider";

const AuthFrame: React.FC<React.PropsWithChildren<{ eyebrow: string; title: string; intro: string }>> = ({ eyebrow, title, intro, children }) => <main className="nest-auth"><section><Link to="/" className="nest-brand"><span className="nest-brand-mark">n</span><span><strong>{productConfig.name}</strong><small>{productConfig.tagline}</small></span></Link><div className="nest-auth-copy"><p>{eyebrow}</p><h1>{title}</h1><span>{intro}</span></div>{children}</section><aside><p>CARE, SHARED.</p><blockquote>“The small things are easier when everyone knows what’s happening.”</blockquote><small>A calm, shared picture of your child’s day.</small></aside></main>;
const ErrorText: React.FC<{ value: string }> = ({ value }) => value ? <p className="nest-form-error" role="alert">{value}</p> : null;
export const SignIn: React.FC = () => { const auth = useNestAuth(); const navigate = useNavigate(); const location = useLocation(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); if (auth.session) return <Navigate to="/nest" replace/>; return <AuthFrame eyebrow="WELCOME BACK" title="Your family, in sync." intro="Pick up exactly where care left off."><form className="nest-auth-form" onSubmit={async(event) => { event.preventDefault(); setBusy(true); setError(""); try { await auth.signIn(email, password); navigate((location.state as { from?: string } | null)?.from ?? "/nest"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Sign in failed"); } finally { setBusy(false); } }}><label>Email<input type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={(event) => setPassword(event.target.value)}/></label><div className="nest-auth-row"><label className="nest-check"><input type="checkbox"/> Remember me</label><Link to="/nest/forgot-password">Forgot password?</Link></div><ErrorText value={error}/><button disabled={busy}>{busy ? "Signing in…" : "Sign in"}</button><p>New to Nest? <Link to="/nest/sign-up">Create an account</Link></p></form></AuthFrame>; };
export const SignUp: React.FC = () => { const auth = useNestAuth(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); if (auth.session) return <Navigate to="/nest/onboarding" replace/>; return <AuthFrame eyebrow="WELCOME TO NEST" title="Care starts with knowing." intro="Create your private family space in a minute."><form className="nest-auth-form" onSubmit={async(event) => { event.preventDefault(); setError(""); try { const result = await auth.signUp(name, email, password); setMessage(result.needsVerification ? "Check your email to verify your account, then return to Nest." : "Account created. You can continue to onboarding."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Sign up failed"); } }}><label>Your name<input required autoComplete="name" value={name} onChange={(event) => setName(event.target.value)}/></label><label>Email<input required type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)}/></label><label>Password<input required minLength={8} type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)}/><small>At least 8 characters</small></label><ErrorText value={error}/>{message && <p className="nest-form-success">{message}</p>}<button>Create account</button><p>Already have an account? <Link to="/nest/sign-in">Sign in</Link></p></form></AuthFrame>; };
export const ForgotPassword: React.FC = () => { const auth = useNestAuth(); const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const [error, setError] = useState(""); return <AuthFrame eyebrow="PASSWORD RESET" title="Let’s get you back in." intro="We’ll send a secure reset link to your email."><form className="nest-auth-form" onSubmit={async(event) => { event.preventDefault(); try { await auth.resetPassword(email); setSent(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not send reset email"); } }}><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)}/></label><ErrorText value={error}/>{sent && <p className="nest-form-success">Check your inbox for the reset link.</p>}<button>Send reset link</button><p><Link to="/nest/sign-in">Back to sign in</Link></p></form></AuthFrame>; };
export const ResetPassword: React.FC = () => { const auth = useNestAuth(); const navigate = useNavigate(); const [password, setPassword] = useState(""); const [error, setError] = useState(""); return <AuthFrame eyebrow="NEW PASSWORD" title="Choose a new password." intro="Use at least eight characters."><form className="nest-auth-form" onSubmit={async(event) => { event.preventDefault(); try { await auth.updatePassword(password); navigate("/nest"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not update password"); } }}><label>New password<input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)}/></label><ErrorText value={error}/><button>Update password</button></form></AuthFrame>; };
