import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { createHouseholdInvitation } from "../application/invitations";
import { useHousehold } from "../application/HouseholdContext";
import { useAuth } from "../auth/AuthProvider";
import { HouseholdInviteRow } from "../infrastructure/supabase/database.types";
import { householdRepository } from "../repositories/householdRepository";

const initials=(name:string)=>name.split(/\s+/).map((part)=>part[0]).join("").slice(0,2).toUpperCase();
const date=(value:string)=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value));

const HouseholdSettings:React.FC=()=>{
  const household=useHousehold();const{session}=useAuth();const[searchParams,setSearchParams]=useSearchParams();
  const me=useMemo(()=>household.members.find((member)=>member.userId===session?.user.id),[household.members,session?.user.id]);
  const owner=household.membership.role==="owner";const[name,setName]=useState(household.household.name);const[displayName,setDisplayName]=useState(me?.displayName??"");const[avatarUrl,setAvatarUrl]=useState(me?.avatarUrl??"");
  const[inviteEmail,setInviteEmail]=useState("");const[inviteLink,setInviteLink]=useState("");const[invites,setInvites]=useState<HouseholdInviteRow[]>([]);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[createName,setCreateName]=useState("");
  const loadInvites=useCallback(async()=>{if(owner)setInvites(await householdRepository.invitations(household.household.id));},[household.household.id,owner]);
  useEffect(()=>{void loadInvites().catch(()=>setMessage("Invitations could not be loaded."));},[loadInvites]);
  const act=async(action:()=>Promise<void>,success:string)=>{setBusy(true);setMessage("");try{await action();setMessage(success);}catch(error){setMessage(error instanceof Error?error.message:"That change could not be saved.");}finally{setBusy(false);}};
  const invite=async(email:string)=>{const link=await createHouseholdInvitation(household.household.id,email);setInviteLink(link);setInviteEmail("");await loadInvites();};
  return <div className="budgy-product-page budgy-household-settings"><header className="budgy-product-header"><div><p className="budgy-eyebrow">Settings</p><h1>Household</h1><p>Manage the people and identity behind your shared plan.</p></div></header>
    {message&&<div className="budgy-inline-notice" role="status">{message}<button type="button" onClick={()=>setMessage("")}>×</button></div>}
    <section className="budgy-product-panel budgy-settings-section"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Household</p><h2>{household.household.name}</h2></div></div><form className="budgy-inline-form" onSubmit={(event)=>{event.preventDefault();void act(async()=>{await householdRepository.rename(household.household.id,name);household.reload();},"Household name updated.");}}><label className="budgy-field"><span>Household name</span><input required disabled={!owner} value={name} onChange={(event)=>setName(event.target.value)}/></label>{owner&&<button className="budgy-button budgy-button--primary" disabled={busy}>Save name</button>}</form>{!owner&&<p className="budgy-supporting-copy">Only a household owner can rename this household.</p>}</section>
    <section className="budgy-product-panel budgy-settings-section"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Members</p><h2>{household.members.length} household member{household.members.length===1?"":"s"}</h2></div></div><div className="budgy-member-table">{household.members.map((member)=><div key={member.userId} className="budgy-member-row"><span className="budgy-member-avatar">{member.avatarUrl?<img src={member.avatarUrl} alt=""/>:initials(member.displayName)}</span><span><b>{member.displayName}</b><small>{member.email}</small></span><span><b>{member.role}</b><small>Joined {date(member.joinedAt)}</small></span>{owner&&member.userId!==session?.user.id?<button className="budgy-button budgy-button--danger-quiet" type="button" disabled={busy} onClick={()=>{if(window.confirm(`Remove ${member.displayName} from this household?`))void act(async()=>{await householdRepository.removeMember(household.household.id,member.userId);household.reload();},`${member.displayName} was removed.`);}}>Remove</button>:<span/>}</div>)}</div></section>
    {owner&&<section className="budgy-product-panel budgy-settings-section"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Invitations</p><h2>Invite a household member</h2></div></div><form className="budgy-inline-form" onSubmit={(event)=>{event.preventDefault();void act(()=>invite(inviteEmail),"Invitation created.");}}><label className="budgy-field"><span>Email address</span><input type="email" required value={inviteEmail} onChange={(event)=>setInviteEmail(event.target.value)} placeholder="partner@example.com"/></label><button className="budgy-button budgy-button--primary" disabled={busy}>Invite member</button></form>{inviteLink&&<div className="budgy-invite-link"><p>Share this private seven-day link with the invited member.</p><code>{inviteLink}</code><button type="button" className="budgy-button budgy-button--quiet" onClick={()=>void navigator.clipboard.writeText(inviteLink)}>Copy link</button></div>}<div className="budgy-invitation-list">{invites.filter((entry)=>!entry.accepted_at).map((entry)=><div key={entry.id}><span><b>{entry.email}</b><small>{new Date(entry.expires_at)>new Date()?`Pending · expires ${date(entry.expires_at)}`:"Expired"}</small></span><div><button type="button" className="budgy-button budgy-button--quiet" disabled={busy} onClick={()=>void act(async()=>{await householdRepository.cancelInvite(entry.id);await invite(entry.email);},"A new invitation was created.")}>Resend</button><button type="button" className="budgy-button budgy-button--danger-quiet" disabled={busy} onClick={()=>void act(async()=>{await householdRepository.cancelInvite(entry.id);await loadInvites();},"Invitation cancelled.")}>Cancel</button></div></div>)}</div></section>}
    <section className="budgy-product-panel budgy-settings-section"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">My profile</p><h2>How your household sees you</h2></div></div><form className="budgy-form" onSubmit={(event)=>{event.preventDefault();void act(async()=>{await householdRepository.updateProfile(displayName,avatarUrl||null);household.reload();},"Your profile was updated.");}}><div className="budgy-form-grid"><label className="budgy-field"><span>Display name</span><input required value={displayName} onChange={(event)=>setDisplayName(event.target.value)}/></label><label className="budgy-field"><span>Email</span><input readOnly value={me?.email??session?.user.email??""}/></label><label className="budgy-field"><span>Avatar URL <small>Optional</small></span><input type="url" value={avatarUrl} onChange={(event)=>setAvatarUrl(event.target.value)} placeholder="https://…"/></label></div><button className="budgy-button budgy-button--primary" disabled={busy}>Save my profile</button></form></section>
    {searchParams.get("create")==="1"&&<section className="budgy-product-panel budgy-settings-section"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">New household</p><h2>Create another household</h2></div></div><form className="budgy-inline-form" onSubmit={(event)=>{event.preventDefault();void act(async()=>{const id=await householdRepository.create(createName,displayName);setSearchParams({});household.switchHousehold(id);},"Household created.");}}><label className="budgy-field"><span>Household name</span><input autoFocus required value={createName} onChange={(event)=>setCreateName(event.target.value)}/></label><button className="budgy-button budgy-button--primary" disabled={busy}>Create household</button></form></section>}
  </div>;
};
export default HouseholdSettings;
