import React,{useMemo,useState}from"react";
import{Dialog}from"../components/Dialog";
import{MoneyInput,MonthPicker,OwnerSelector,ProgressBar}from"../components/Controls";
import{BudgetItemForm,TransactionForm}from"../components/Forms";
import{accountBalances,budgetItemActual,monthlyControl,spendingPace}from"../domain/accounts";
import{createId}from"../domain/id";
import{formatMoney}from"../domain/money";
import{BudgetItem,FinancialAccount,FinancialAccountType,HOUSEHOLD_OWNER,Transaction}from"../domain/types";
import{ownerLabel}from"../domain/ownership";
import{useAuth}from"../auth/AuthProvider";
import{useBudgyStore}from"../store/BudgyStore";
import{allocationPurpose,calculateAllocationProgress}from"../domain/allocations";

const typeLabel:Record<FinancialAccountType,string>={current_account:"Current account",savings_account:"Savings account",credit_card:"Credit card",cash:"Cash",other:"Other"};
const Money:React.FC=()=>{const{data,month,plan,setMonth,updateData,updateMonth}=useBudgyStore();const{session}=useAuth();const[accountOpen,setAccountOpen]=useState(false);const[paymentCard,setPaymentCard]=useState<FinancialAccount|null>(null);const[planCard,setPlanCard]=useState<FinancialAccount|null>(null);
  const[account,setAccount]=useState<FinancialAccount>({id:createId(),name:"",owner:session!.user.id,type:"current_account",currency:"GBP",openingBalance:0,isActive:true});
  const balances=useMemo(()=>accountBalances(data.accounts,data.transactions),[data.accounts,data.transactions]);const income=plan.income.reduce((sum,row)=>sum+row.amount,0);const control=monthlyControl(plan.budget,data.transactions,month,income,plan.savings);const creditDebt=balances.filter((row)=>row.type==="credit_card").reduce((sum,row)=>sum+row.balance,0);
  const ownerGroups=[HOUSEHOLD_OWNER,...data.members.map((member)=>member.id)].map((owner)=>({owner,items:plan.budget.filter((item)=>item.owner===owner&&item.trackActuals!==false&&allocationPurpose(item)==="spending")})).filter((group)=>group.items.length);
  const existingCardPlan=planCard?plan.budget.find((item)=>allocationPurpose(item)==="debt_payment"&&item.linkedAccountId===planCard.id):undefined;
  const paceDate=(()=>{const now=new Date();const key=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;if(key===month)return now;const[y,m]=month.split("-").map(Number);return new Date(y,m,0);})();
  const newAccount=()=>{setAccount({id:createId(),name:"",owner:session!.user.id,type:"current_account",currency:"GBP",openingBalance:0,isActive:true});setAccountOpen(true);};
  const saveAccount=(event:React.FormEvent)=>{event.preventDefault();updateData((current)=>({...current,accounts:current.accounts.some((entry)=>entry.id===account.id)?current.accounts.map((entry)=>entry.id===account.id?account:entry):[...current.accounts,account]}));setAccountOpen(false);};
  const addTransaction=(transaction:Transaction)=>{updateData((current)=>({...current,transactions:[...current.transactions,transaction]}));setPaymentCard(null);};
  return <div className="budgy-product-page budgy-money-page"><header className="budgy-product-header"><div><p className="budgy-eyebrow">Monthly control</p><h1>Money</h1><p>What remains this month, and where the money is moving.</p></div><div className="budgy-header-actions"><MonthPicker month={month} onChange={setMonth}/><button className="budgy-button budgy-button--primary" onClick={newAccount}>+ Add account</button></div></header>
    <section className="budgy-money-summary"><div><span>Available to spend</span><strong>{formatMoney(control.leftToSpend)}</strong></div><div><span>Spent so far</span><strong>{formatMoney(control.spent)}</strong></div><div><span>Unallocated income</span><strong>{formatMoney(control.unallocatedIncome)}</strong></div><div><span>Savings target</span><strong>{formatMoney(plan.savings)}</strong></div><div className="is-debt"><span>Credit-card debt</span><strong>{formatMoney(creditDebt)}</strong></div></section>
    <section className="budgy-money-layout"><div><div className="budgy-budget-toolbar"><div><p className="budgy-eyebrow">Allowances</p><h2>Left to spend</h2></div></div>{ownerGroups.map((group)=><section className="budgy-product-panel budgy-allowance-group" key={group.owner}><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">{ownerLabel(group.owner,data.members)}</p><h2>Monthly allowances</h2></div></div>{group.items.map((item)=>{const actual=budgetItemActual(item,data.transactions,month);const pace=spendingPace(actual.spent,actual.planned,paceDate);return <article className="budgy-allowance" key={item.id}><div><span><b>{item.name}</b><small>{item.group} · {pace.status}</small></span><strong>{formatMoney(actual.remaining)}</strong></div><ProgressBar value={actual.usedRate} tone={actual.remaining<0?"warning":"default"}/><dl><div><dt>Budget</dt><dd>{formatMoney(actual.planned)}</dd></div><div><dt>Spent</dt><dd>{formatMoney(actual.spent)}</dd></div><div><dt>Used</dt><dd>{Math.round(actual.usedRate*100)}%</dd></div></dl><p>{actual.remaining<0?`This allocation has been exceeded by ${formatMoney(Math.abs(actual.remaining))}.`:pace.status==="Watch spending"?`${Math.round(pace.spentRate*100)}% has been used with ${Math.round((1-pace.elapsedRate)*100)}% of the month remaining.`:`${formatMoney(actual.remaining)} remains in ${item.name.toLowerCase()}.`}</p></article>;})}</section>)}</div>
      <aside><div className="budgy-budget-toolbar"><div><p className="budgy-eyebrow">Payment sources</p><h2>Accounts</h2></div></div><div className="budgy-account-list">{balances.length?balances.map((entry)=>{const paymentPlan=plan.budget.find((item)=>allocationPurpose(item)==="debt_payment"&&item.linkedAccountId===entry.id);const paymentProgress=paymentPlan?calculateAllocationProgress(paymentPlan,data.transactions,month):null;return <article className={`budgy-account-card ${entry.type==="credit_card"?"is-credit-card":""}`} key={entry.id}><p>{typeLabel[entry.type]} · {ownerLabel(entry.owner,data.members)}</p><h3>{entry.name}</h3>{entry.type==="credit_card"?<><dl><div><dt>Outstanding</dt><dd>{formatMoney(entry.balance)}</dd></div><div><dt>Statement</dt><dd>{entry.statementBalance===undefined?"—":formatMoney(entry.statementBalance)}</dd></div><div><dt>Limit</dt><dd>{entry.creditLimit===undefined?"—":formatMoney(entry.creditLimit)}</dd></div><div><dt>Available</dt><dd>{entry.availableCredit===undefined?"—":formatMoney(entry.availableCredit)}</dd></div><div><dt>Payment due</dt><dd>{entry.paymentDueDate?new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"}).format(new Date(`${entry.paymentDueDate}T12:00:00`)):"—"}</dd></div></dl>{paymentPlan&&<p className="budgy-card-payment-plan"><span>{paymentPlan.name}</span><b>{formatMoney(paymentProgress?.actual??0)} of {formatMoney(paymentPlan.amount)} paid</b></p>}</>:<div className="budgy-account-balance"><span>Current balance</span><strong>{formatMoney(entry.balance)}</strong></div>}<div className="budgy-account-actions">{entry.type==="credit_card"&&<><button className="budgy-button budgy-button--card-primary" onClick={()=>setPaymentCard(entry)}>Record payment</button><button className="budgy-button budgy-button--card-secondary" onClick={()=>setPlanCard(entry)}>Plan monthly payment</button></>}<button className={`budgy-button ${entry.type==="credit_card"?"budgy-button--card-secondary":"budgy-button--quiet"}`} onClick={()=>{setAccount(entry);setAccountOpen(true);}}>Edit details</button></div></article>}):<div className="budgy-product-empty"><h2>Add an account</h2><p>Add the accounts and cards your household uses.</p><button className="budgy-button budgy-button--primary" type="button" onClick={newAccount}>Add an account</button></div>}</div></aside></section>
    <Dialog open={accountOpen} title={data.accounts.some((entry)=>entry.id===account.id)?"Edit payment account":"Add payment account"} onClose={()=>setAccountOpen(false)}><form className="budgy-form" onSubmit={saveAccount}><label className="budgy-field"><span>Account name</span><input autoFocus required value={account.name} onChange={(event)=>setAccount({...account,name:event.target.value})} placeholder="Main current account"/></label><div className="budgy-form-grid"><OwnerSelector value={account.owner} onChange={(owner)=>setAccount({...account,owner})}/><label className="budgy-field"><span>Account type</span><select value={account.type} onChange={(event)=>setAccount({...account,type:event.target.value as FinancialAccountType})}>{Object.entries(typeLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><MoneyInput label={account.type==="credit_card"?"Opening debt":"Opening balance"} value={account.openingBalance} onChange={(openingBalance)=>setAccount({...account,openingBalance})}/>{account.type==="credit_card"&&<><MoneyInput label="Credit limit" value={account.creditLimit??0} onChange={(creditLimit)=>setAccount({...account,creditLimit})}/><MoneyInput label="Statement balance" value={account.statementBalance??0} onChange={(statementBalance)=>setAccount({...account,statementBalance})}/><label className="budgy-field"><span>Payment due</span><input type="date" value={account.paymentDueDate??""} onChange={(event)=>setAccount({...account,paymentDueDate:event.target.value||undefined})}/></label></>}<label className="budgy-check"><input type="checkbox" checked={account.isActive} onChange={(event)=>setAccount({...account,isActive:event.target.checked})}/><span>Available for new transactions</span></label></div><div className="budgy-dialog-actions"><button type="button" className="budgy-button budgy-button--quiet" onClick={()=>setAccountOpen(false)}>Cancel</button><button className="budgy-button budgy-button--primary">Save account</button></div></form></Dialog>
    <Dialog open={!!paymentCard} title={`Record payment to ${paymentCard?.name??"card"}`} description="This reduces card debt and bank cash. It does not count as new monthly spending." onClose={()=>setPaymentCard(null)}>{paymentCard&&<TransactionForm month={month} initialType="credit_card_payment" initialDestinationAccountId={paymentCard.id} onSave={addTransaction} onCancel={()=>setPaymentCard(null)}/>}</Dialog>
    <Dialog open={!!planCard} title={`${planCard?.name??"Card"} payment plan`} description={`Choose how much household income to put toward this debt in ${month}. No payment is recorded yet.`} onClose={()=>setPlanCard(null)}>{planCard&&<BudgetItemForm item={existingCardPlan??{id:createId(),name:`${planCard.name} payoff`,group:"Debt payments",owner:HOUSEHOLD_OWNER,amount:0,recurring:true,trackActuals:true,purpose:"debt_payment",linkedAccountId:planCard.id}} categories={data.categories} accounts={data.accounts} transactions={data.transactions} onCancel={()=>setPlanCard(null)} onSave={(item:BudgetItem)=>{updateMonth((current)=>({...current,budget:[...current.budget.filter((entry)=>!(allocationPurpose(entry)==="debt_payment"&&entry.linkedAccountId===planCard.id)),item]}));setPlanCard(null);}}/>}</Dialog>
  </div>;
};
export default Money;
