import React,{useEffect,useMemo,useState}from"react";
import{Link}from"react-router-dom";
import MonthHero from"../components/MonthHero";
import SpendingDonut from"../components/SpendingDonut";
import{MonthPicker}from"../components/Controls";
import{buildHomeViewModel,HomeCategoryProgress}from"../domain/home";
import{formatCompactMoney,formatMoney}from"../domain/money";
import{transactionBudgetMonth}from"../domain/months";
import{useBudgyStore}from"../store/BudgyStore";
import{useHousehold}from"../application/HouseholdContext";
import{ActivityEvent,activityRepository}from"../repositories/activityRepository";

const percentage=(value:number)=>`${(value*100).toFixed(1)}%`;
const resultCopy=(category:HomeCategoryProgress,complete:boolean)=>category.remaining<0?`${complete?"Finished ":""}${formatMoney(Math.abs(category.remaining))} over plan`:category.remaining===0?complete?"Finished on plan":"£0 left":`${formatMoney(category.remaining)} ${complete?"under plan":"left"}`;

const Overview:React.FC=()=>{
  const{data,month,setMonth}=useBudgyStore();const household=useHousehold();const[activity,setActivity]=useState<ActivityEvent[]|null>(null);
  const model=useMemo(()=>buildHomeViewModel(data,month),[data,month]);const complete=model.lifecycle==="complete";const future=model.lifecycle==="future";
  const actualGroups=useMemo(()=>model.actualCategories.map((category)=>({group:category.key,amount:category.spent,shareOfSpending:model.actualSpending?category.spent/model.actualSpending:0})).filter((group)=>group.amount>0),[model.actualCategories,model.actualSpending]);
  const selectedTransactions=data.transactions.filter((row)=>transactionBudgetMonth(row)===month).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);
  useEffect(()=>{let active=true;activityRepository.list(household.household.id,3).then((events)=>{if(active)setActivity(events);}).catch(()=>{if(active)setActivity([]);});return()=>{active=false;};},[household.household.id,data]);
  const activitySentence=(event:ActivityEvent)=>{const label=String(event.metadata.label??event.entityType.replaceAll("_"," "));const amount=Number(event.metadata.new_amount_pence);if(event.eventType==="budget.reallocated")return`${event.actor} moved ${formatMoney(Number(event.metadata.amount_pence))} from ${String(event.metadata.from_label)} to ${String(event.metadata.to_label)}`;if(event.eventType==="transactions.insert"){const type=String(event.metadata.type??"transaction").replaceAll("_"," ");return`${event.actor} recorded${Number.isFinite(amount)?` ${formatMoney(amount)}`:""} as ${type}${label?` · ${label}`:""}`;}if(event.eventType.endsWith(".insert"))return`${event.actor} created ${label}`;if(event.eventType.endsWith(".delete"))return`${event.actor} removed ${label}`;return`${event.actor} updated ${label}`;};
  const showCategoryProgress=model.lifecycle==="active"||complete||(future&&model.hasActualSpending);
  const showPlan=model.plan.income!==0||model.plan.spending!==0||model.plan.debtPayments!==0||model.plan.savings!==0;
  return <div className="budgy-overview budgy-home-v2">
    <header className="budgy-page-header"><div><p className="budgy-eyebrow">Household overview</p><h1>Your money, moving together.</h1><p className="budgy-page-intro">{model.copy.headline}</p></div><MonthPicker month={month} onChange={setMonth}/></header>
    <MonthHero model={model} hasAccounts={data.accounts.length>0}/>

    {model.earlyTransactions.length>0&&<section className="budgy-panel budgy-early-activity"><div className="budgy-panel-heading"><div><p className="budgy-eyebrow">Already counted toward {model.monthName.split(" ")[0]}</p><h2>Recorded before the month began</h2></div><Link className="budgy-text-link" to={`/budgy/transactions?budgetMonth=${month}`}>View transactions <span>→</span></Link></div><p>These transactions keep their real payment date while counting against {model.monthName}’s budget.</p><div>{model.earlyTransactions.slice(0,3).map((row)=><span key={row.id}><b>{row.description}</b><small>Paid {new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"}).format(new Date(`${row.date}T12:00:00`))}</small><strong>{formatMoney(row.type==="refund"?-row.amount:row.amount)}</strong></span>)}</div></section>}

    {showCategoryProgress&&<section className="budgy-home-performance"><article className="budgy-panel"><div className="budgy-panel-heading"><div><p className="budgy-eyebrow">{complete?`How ${model.monthName.split(" ")[0]} finished`:"How you’re doing"}</p><h2>{complete?"Final category results":"Category progress"}</h2></div><Link className="budgy-text-link" to="/budgy/budget">View full budget <span>→</span></Link></div><div className="budgy-home-category-list">{model.categories.slice(0,5).map((category)=><Link key={category.key} className={`budgy-home-category is-${category.status}`} to={`/budgy/transactions?category=${encodeURIComponent(category.key)}&budgetMonth=${month}`}><div><b>{category.key}</b><span>{formatMoney(category.spent)} of {formatMoney(category.planned)}</span></div><strong>{resultCopy(category,complete)}</strong><div className="budgy-home-category-track" role="progressbar" aria-label={`${category.key}: ${formatMoney(category.spent)} spent of ${formatMoney(category.planned)} planned`} aria-valuemin={0} aria-valuemax={category.planned} aria-valuenow={category.spent}><i style={{width:`${Math.min(100,Math.max(0,category.usedRate*100))}%`}}/></div></Link>)}</div></article>{model.attention.length>0&&<aside className="budgy-panel budgy-attention"><div className="budgy-panel-heading"><div><p className="budgy-eyebrow">Needs attention</p><h2>Worth a look</h2></div></div><div>{model.attention.map((item)=><Link key={`${item.kind}-${item.title}`} to={item.to}><span><b>{item.title}</b><small>{item.detail}</small></span><span aria-hidden="true">→</span></Link>)}</div></aside>}</section>}

    {model.hasActualSpending&&<section className="budgy-panel budgy-actual-breakdown"><div className="budgy-panel-heading"><div><p className="budgy-eyebrow">{complete?`Where ${model.monthName.split(" ")[0]} went`:"Where it went"}</p><h2>Actual spending</h2></div><Link className="budgy-text-link" to={`/budgy/transactions?budgetMonth=${month}`}>Open transactions <span>→</span></Link></div><div className="budgy-actual-breakdown-layout"><SpendingDonut groups={actualGroups} total={model.actualSpending} label="Actual spending" centreLabel="Spent"/><div className="budgy-actual-plan-list">{model.actualCategories.map((category)=><Link key={category.key} to={`/budgy/transactions?category=${encodeURIComponent(category.key)}&budgetMonth=${month}`}><span>{category.key}</span><strong>{formatMoney(category.spent)} <small>/ {formatMoney(category.planned)}</small></strong></Link>)}</div></div></section>}

    {showPlan&&<section className={`budgy-panel budgy-home-plan ${model.lifecycle==="setup"||future||model.lifecycle==="ready"?"is-prominent":""}`}><div className="budgy-panel-heading"><div><p className="budgy-eyebrow">Your plan</p><h2>What your money is meant to do</h2></div><Link className="budgy-text-link" to="/budgy/budget">View budget <span>→</span></Link></div><div className="budgy-home-plan-metrics"><div><span>Income</span><b>{formatMoney(model.plan.income)}</b></div><div><span>For spending</span><b>{formatMoney(model.plan.spending)}</b></div>{model.plan.debtPayments>0&&<div><span>Toward debt</span><b>{formatMoney(model.plan.debtPayments)}</b></div>}<div><span>Savings target</span><b>{formatMoney(model.plan.savings)}</b></div><div><span>Left to allocate <i className="budgy-info-dot" tabIndex={0} aria-label="Left to allocate means income that has not been assigned to spending, debt payments, or savings." title="Income that hasn’t been assigned to spending, debt payments, or savings.">i</i></span><b>{formatMoney(model.plan.remaining)}</b></div></div>{model.plan.income>0&&<div className="budgy-home-allocation"><div role="img" aria-label={`${percentage(model.allocation.spendingRate)} spending, ${percentage(model.allocation.debtRate)} debt payments, ${percentage(model.allocation.savingsRate)} savings and ${percentage(model.allocation.unallocatedRate)} unallocated`}><i style={{width:percentage(Math.max(0,model.allocation.spendingRate))}}/><i style={{width:percentage(Math.max(0,model.allocation.debtRate))}}/><i style={{width:percentage(Math.max(0,model.allocation.savingsRate))}}/><i style={{width:percentage(Math.max(0,model.allocation.unallocatedRate))}}/></div><p><span>Spending <b>{percentage(model.allocation.spendingRate)}</b></span>{model.plan.debtPayments>0&&<span>Debt <b>{percentage(model.allocation.debtRate)}</b></span>}<span>Savings <b>{percentage(model.allocation.savingsRate)}</b></span><span>Unallocated <b>{percentage(model.allocation.unallocatedRate)}</b></span></p></div>}</section>}

    {(model.plan.savings>0||model.actualSavings!==0)&&<section className="budgy-panel budgy-home-savings"><div><p className="budgy-eyebrow">Savings</p><h2>{model.actualSavings!==0?complete?"Saved this month":"Saved so far":"Savings target"}</h2><strong>{formatMoney(model.actualSavings!==0?model.actualSavings:model.plan.savings)}</strong><p>{model.actualSavings!==0?`of ${formatMoney(model.plan.savings)} monthly target`:`A target, not money recorded as saved.`}</p></div><div><span>At this planned rate</span><b>{formatCompactMoney(model.projection.twelveMonths)} in 12 months</b><b>{formatCompactMoney(model.projection.fiveYears)} in 5 years</b><Link className="budgy-text-link" to="/budgy/projections">Explore projection <span>→</span></Link></div></section>}

    {(activity?.length||selectedTransactions.length>0)&&<section className="budgy-panel budgy-home-activity"><div className="budgy-panel-heading"><div><p className="budgy-eyebrow">Shared activity</p><h2>Recent household activity</h2></div><Link className="budgy-text-link" to="/budgy/transactions">View all <span>→</span></Link></div>{activity?.length?<div className="budgy-recent-list">{activity.map((event)=><div key={event.id}><span><b>{activitySentence(event)}</b><small>{new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(event.createdAt))}</small></span></div>)}</div>:<div className="budgy-recent-list">{selectedTransactions.map((row)=><div key={row.id}><span><b>{row.description}</b><small>{row.type.replaceAll("_"," ")} · {new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"}).format(new Date(`${row.date}T12:00:00`))}</small></span><strong>{formatMoney(row.amount)}</strong></div>)}</div>}</section>}
  </div>;
};
export default Overview;
