import React,{useMemo}from"react";
import{Link}from"react-router-dom";
import{MonthPicker,monthLabel,ProgressBar}from"../components/Controls";
import{buildMonthlyReport}from"../domain/reports";
import{formatMoney}from"../domain/money";
import{ownerLabel}from"../domain/ownership";
import{useBudgyStore}from"../store/BudgyStore";

const signed=(value:number)=>`${value>0?"+":value<0?"−":""}${formatMoney(Math.abs(value))}`;
const Reports:React.FC=()=>{const{data,month,setMonth}=useBudgyStore();const report=useMemo(()=>buildMonthlyReport(data,month,(owner)=>ownerLabel(owner,data.members)),[data,month]);
  return <div className="budgy-product-page budgy-reports"><header className="budgy-product-header"><div><p className="budgy-eyebrow">Monthly report</p><h1>{monthLabel(month)}</h1><p>A factual statement built from the activity recorded in Budgy.</p></div><MonthPicker month={month} onChange={setMonth}/></header>
    <p className="budgy-report-completeness">Cash flow uses {report.transactionCount} transaction{report.transactionCount===1?"":"s"} dated this month. Budget performance uses {report.budgetTransactionCount} entr{report.budgetTransactionCount===1?"y":"ies"} assigned to {monthLabel(month)}.{report.accounts.some((account)=>!account.complete)&&" Some account opening balances have not been provided."}</p>
    <section className="budgy-report-answers"><article><span>Income received</span><strong>{formatMoney(report.income)}</strong><small>Cash received by transaction date</small></article><article><span>Actual spending</span><strong>{formatMoney(report.spending)}</strong><small>Expenses only · payments excluded</small></article><article><span>Debt repayments</span><strong>{formatMoney(report.cashDebtPayments)}</strong><small>Cash paid to credit cards</small></article><article><span>Savings transferred</span><strong>{formatMoney(report.savings)}</strong><small>Actual movement into savings</small></article></section>
    <section className="budgy-report-plan-summary" aria-label="Planned and actual summary"><div><span>Income</span><small>Planned {formatMoney(report.plannedIncome)}</small><b>Assigned {formatMoney(report.budgetIncome)}</b></div><div><span>Spending</span><small>Planned {formatMoney(report.plannedSpending)}</small><b>Assigned {formatMoney(report.budgetSpending)}</b></div><div><span>Debt payments</span><small>Planned {formatMoney(report.plannedDebtPayments)}</small><b>Paid toward plan {formatMoney(report.actualDebtPayments)}</b></div><div><span>Savings</span><small>Target {formatMoney(report.plannedSavings)}</small><b>Cash moved {formatMoney(report.savings)}</b></div></section>
    <section className="budgy-report-metrics"><div><span>Net cash flow</span><b>{formatMoney(report.netCashFlow)}</b></div><div><span>Savings rate</span><b>{(report.savingsRate*100).toFixed(1)}%</b></div><div><span>Budget utilisation</span><b>{(report.budgetUtilisation*100).toFixed(1)}%</b></div><div><span>Credit-card debt</span><b>{formatMoney(report.creditCardDebt)}</b></div><div><span>Unallocated plan</span><b>{formatMoney(report.unallocatedMoney)}</b></div></section>
    <section className="budgy-product-panel budgy-report-plan"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Budget performance</p><h2>Planned vs assigned actuals</h2></div></div><div className="budgy-report-table"><div className="budgy-report-table-head"><span>Category</span><span>Planned</span><span>Actual</span><span>Difference</span></div>{report.planVsActual.map((row)=><div key={row.key}><Link to={`/budgy/transactions?category=${encodeURIComponent(row.key)}&budgetMonth=${month}`}>{row.label}</Link><span>{formatMoney(row.planned??0)}</span><span>{formatMoney(row.amount)}</span><span className={(row.difference??0)<0?"is-negative":"is-positive"}>{formatMoney(Math.abs(row.difference??0))} {(row.difference??0)>=0?"under":"over"}</span><ProgressBar value={(row.planned??0)?row.amount/(row.planned??1):row.amount?1:0} tone={(row.difference??0)<0?"warning":"default"}/></div>)}</div></section>
    {!!report.plannedVsActualIncome.length&&<section className="budgy-product-panel budgy-report-plan"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Money in</p><h2>Planned vs actual income</h2></div></div><div className="budgy-report-table"><div className="budgy-report-table-head"><span>Source</span><span>Planned</span><span>Actual</span><span>Difference</span></div>{report.plannedVsActualIncome.map((row)=><div key={row.key}><span>{row.label}</span><span>{formatMoney(row.planned??0)}</span><span>{formatMoney(row.amount)}</span><span className={(row.difference??0)<0?"is-negative":"is-positive"}>{signed(row.difference??0)}</span></div>)}</div></section>}
    {!!report.budgetIncome&&<div className="budgy-report-grid"><section className="budgy-product-panel"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Assigned income</p><h2>By income type</h2></div></div><div className="budgy-report-member-list">{report.incomeBreakdown.map((row)=><div key={row.key}><span><b>{row.label}</b><small>{(row.percentage*100).toFixed(1)}% of assigned income</small></span><strong>{formatMoney(row.amount)}</strong></div>)}</div></section><section className="budgy-product-panel"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Assigned income</p><h2>By source</h2></div></div><div className="budgy-report-member-list">{report.incomeBySource.map((row)=><div key={row.key}><span><b>{row.label}</b><small>{(row.percentage*100).toFixed(1)}% of assigned income</small></span><strong>{formatMoney(row.amount)}</strong></div>)}</div></section><section className="budgy-product-panel"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Assigned income</p><h2>By owner</h2></div></div><div className="budgy-report-member-list">{report.incomeByMember.map((row)=><div key={row.key}><span><b>{row.label}</b><small>{(row.percentage*100).toFixed(1)}% of assigned income</small></span><strong>{formatMoney(row.amount)}</strong></div>)}</div></section></div>}
    <div className="budgy-report-grid"><section className="budgy-product-panel"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Assigned spending</p><h2>Where did the budget go?</h2></div></div><div className="budgy-report-bars">{report.categories.filter((row)=>row.amount!==0).map((row)=><Link to={`/budgy/transactions?category=${encodeURIComponent(row.key)}&budgetMonth=${month}`} key={row.key}><span><b>{row.label}</b><small>{(row.percentage*100).toFixed(1)}%</small></span><strong>{formatMoney(row.amount)}</strong><i><span style={{width:`${Math.max(0,row.percentage)*100}%`}}/></i></Link>)}</div>{!report.budgetSpending&&<p className="budgy-report-empty">No expenses are assigned to this budget month.</p>}</section>
      <section className="budgy-product-panel"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Ownership, not entry</p><h2>Who spent what?</h2></div></div><div className="budgy-report-member-list">{report.members.map((row)=><div key={row.key}><span><b>{row.label}</b><small>{(row.percentage*100).toFixed(1)}% of recorded spending</small></span><strong>{formatMoney(row.amount)}</strong></div>)}</div>{!report.members.length&&<p className="budgy-report-empty">Member spending will appear after expenses are recorded.</p>}</section></div>
    <section className="budgy-product-panel"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Money sources</p><h2>Account activity</h2></div></div><div className="budgy-report-accounts">{report.accounts.map((account)=><article key={account.accountId} className={account.type==="credit_card"?"is-card":""}><p>{account.type.replaceAll("_"," ")}</p><h3>{account.name}</h3>{account.type==="credit_card"?<dl><div><dt>Opening debt</dt><dd>{formatMoney(account.opening)}</dd></div><div><dt>Purchases</dt><dd>{formatMoney(account.purchases)}</dd></div><div><dt>Payments</dt><dd>{formatMoney(account.payments)}</dd></div><div><dt>Refunds</dt><dd>{formatMoney(account.refunds)}</dd></div><div><dt>Closing debt</dt><dd>{formatMoney(account.closing)}</dd></div><div><dt>Available credit</dt><dd>{account.availableCredit===undefined?"—":formatMoney(account.availableCredit)}</dd></div></dl>:<dl><div><dt>Opening balance</dt><dd>{formatMoney(account.opening)}</dd></div><div><dt>Money in</dt><dd>{formatMoney(account.moneyIn)}</dd></div><div><dt>Money out</dt><dd>{formatMoney(account.moneyOut)}</dd></div><div><dt>Closing balance</dt><dd>{formatMoney(account.closing)}</dd></div></dl>}</article>)}</div></section>
    <div className="budgy-report-grid"><section className="budgy-product-panel"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Your month</p><h2>Recorded highlights</h2></div></div><ol className="budgy-month-story">{report.observations.map((observation,index)=><li key={observation}><span>{String(index+1).padStart(2,"0")}</span>{observation}</li>)}</ol></section>{report.comparison&&<section className="budgy-product-panel"><div className="budgy-product-panel-heading"><div><p className="budgy-eyebrow">Compared with {monthLabel((()=>{const[y,m]=month.split("-").map(Number);const d=new Date(y,m-2,1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;})())}</p><h2>Month-over-month</h2></div></div><dl className="budgy-report-comparison"><div><dt>Cash income</dt><dd>{signed(report.comparison.income)}</dd></div><div><dt>Cash spending</dt><dd>{signed(report.comparison.spending)}</dd></div><div><dt>Cash savings</dt><dd>{signed(report.comparison.savings)}</dd></div><div><dt>Credit-card debt</dt><dd>{signed(report.comparison.creditCardDebt)}</dd></div>{report.comparison.categoryChanges.slice(0,3).map((row)=><div key={row.key}><dt>{row.key} budget</dt><dd>{signed(row.amount)}</dd></div>)}</dl></section>}</div>
  </div>;
};
export default Reports;
