import {createBlankUserData,UserScopedLocalRepository} from "./fitnessDataRepository";
const user=(id,name)=>({id,user_metadata:{first_name:name}});
describe("Vela account data isolation",()=>{
 beforeEach(()=>localStorage.clear());
 test("creates an empty non-demo fitness profile from auth identity",()=>{const data=createBlankUserData(user("user-a","Juwon"));expect(data.profile.name).toBe("Juwon");expect(data.profile.onboarded).toBe(false);expect(data.workouts).toEqual([]);expect(data.measurements).toEqual([]);});
 test("keeps workout, nutrition and progress caches scoped by authenticated user",()=>{const a=new UserScopedLocalRepository("user-a");const b=new UserScopedLocalRepository("user-b");const aData=createBlankUserData(user("user-a","A"));aData.workouts=[{id:"a-workout",title:"A",focus:"A",date:"2026-10-03",estimatedMinutes:30,status:"active",exercises:[]}];aData.measurements=[{id:"a-weight",date:"2026-10-03",weightKg:80}];aData.nutritionDays=[{date:"2026-10-03",extraCalories:200,extraProtein:20,extraCarbs:10,extraFat:5,waterMl:500}];a.save(aData);expect(b.load()).toBeNull();const bData=createBlankUserData(user("user-b","B"));b.save(bData);expect(b.load().workouts).toEqual([]);expect(b.load().measurements).toEqual([]);expect(a.load().workouts[0].id).toBe("a-workout");expect(a.load().measurements[0].weightKg).toBe(80);});
 test("restores an unfinished workout after a refresh",()=>{const repository=new UserScopedLocalRepository("user-a");const data=createBlankUserData(user("user-a","A"));data.workouts=[{id:"active",title:"Upper",focus:"Strength",date:"2026-10-03",estimatedMinutes:60,status:"active",startedAt:"2026-10-03T10:00:00Z",exercises:[]}];repository.save(data);expect(new UserScopedLocalRepository("user-a").load().workouts[0]).toMatchObject({id:"active",status:"active"});});
 test("clearing one account cache never clears another account",()=>{const a=new UserScopedLocalRepository("user-a");const b=new UserScopedLocalRepository("user-b");a.save(createBlankUserData(user("user-a","A")));b.save(createBlankUserData(user("user-b","B")));a.clear();expect(a.load()).toBeNull();expect(b.load().profile.name).toBe("B");});
});
