import { demoProfile } from "../data/demo";
import { exerciseById } from "../data/exercises";
import { compressWorkout, generateWorkout, rankSubstitutions, recommendProgression } from "./training";

describe("Vela training engine",()=>{
 test("generates a data-driven workout using available equipment",()=>{const workout=generateWorkout(demoProfile,0,new Date("2026-10-02T12:00:00Z"));expect(workout.exercises.length).toBeGreaterThanOrEqual(5);workout.exercises.forEach((item)=>exerciseById(item.exerciseId).equipment.forEach((equipment)=>expect(equipment==="bodyweight"||demoProfile.equipment.includes(equipment)).toBe(true)));});
 test("supports dumbbell-only profiles",()=>{const workout=generateWorkout({...demoProfile,equipment:["bodyweight","dumbbell"],daysPerWeek:3},0);workout.exercises.forEach((item)=>exerciseById(item.exerciseId).equipment.forEach((equipment)=>expect(["bodyweight","dumbbell"].includes(equipment)).toBe(true)));});
 test("keeps every day possible with only bodyweight, dumbbells and a bench",()=>{const profile={...demoProfile,equipment:["bodyweight","dumbbell","bench"],daysPerWeek:4};for(let day=0;day<4;day+=1){const workout=generateWorkout(profile,day);expect(workout.exercises.length).toBeGreaterThanOrEqual(4);workout.exercises.forEach(item=>exerciseById(item.exerciseId).equipment.forEach(equipment=>expect(profile.equipment).toContain(equipment)));}});
 test("prefers curated movements over obscure variants",()=>{const workout=generateWorkout(demoProfile,0);const core=workout.exercises.filter(item=>exerciseById(item.exerciseId).catalogueTier==="core");expect(core.length).toBeGreaterThanOrEqual(Math.ceil(workout.exercises.length/2));});
 test("compresses a session without dropping priority compounds",()=>{const workout=generateWorkout(demoProfile,0);const short=compressWorkout(workout,20);expect(short.estimatedMinutes).toBe(20);expect(short.exercises.length).toBe(3);expect(short.exercises[0].id).toBe(workout.exercises[0].id);});
 test("progresses only after the top of the rep range is owned",()=>{expect(recommendProgression([8,10],26,[10,10,10],2).action).toBe("increase");expect(recommendProgression([8,10],26,[10,9,8],2).action).toBe("hold");expect(recommendProgression([8,10],26,[6,5,5],0).action).toBe("reduce");});
 test("ranks substitutions by movement intent",()=>{const source=exerciseById("barbell-bench");const alternatives=rankSubstitutions(source,demoProfile);expect(alternatives.length).toBeGreaterThan(0);expect(alternatives[0].category).toBe("chest");expect(alternatives[0].movementPattern).toBe("push-horizontal");});
 test("excludes dislikes and unavailable equipment from substitutions",()=>{const source=exerciseById("barbell-bench");const base=rankSubstitutions(source,{...demoProfile,equipment:["bodyweight","dumbbell","bench"]});expect(base.length).toBeGreaterThan(0);const blocked=base[0].id;const alternatives=rankSubstitutions(source,{...demoProfile,equipment:["bodyweight","dumbbell","bench"],dislikedExercises:[blocked]});expect(alternatives.map(item=>item.id)).not.toContain(blocked);alternatives.forEach(item=>item.equipment.forEach(equipment=>expect(["bodyweight","dumbbell","bench"].includes(equipment)).toBe(true)));});
});
