import React,{useState}from"react";
import{useAuth}from"./AuthProvider";
import{describeBudgyError}from"../application/errors";

const friendly=(error:unknown)=>describeBudgyError(error);
export const AuthPage:React.FC=()=>{const invite=new URLSearchParams(window.location.hash.replace(/^#/,"")).get("invite");if(invite)sessionStorage.setItem("budgy.pendingInvite",invite);const{signIn,signUp,resetPassword}=useAuth();const[mode,setMode]=useState<"signin"|"signup"|"forgot">("signin");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[displayName,setDisplayName]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setMessage("");try{if(mode==="signin")await signIn(email,password);else if(mode==="signup"){await signUp(email,password,displayName);setMessage("Check your email to confirm your account, then sign in.");}else{await resetPassword(email);setMessage("If that address has an account, a reset link is on its way.");}}catch(error){setMessage(friendly(error));}finally{setBusy(false);}};
  return <main className="budgy-auth"><section className="budgy-auth-brand"><div className="budgy-brand"><span className="budgy-brand-mark">B</span><span className="budgy-brand-name">budgy</span></div><div><p className="budgy-eyebrow">Shared money, shared clarity</p><h1>Plan a life together,<br/>without the spreadsheet.</h1><p>A private household workspace for budgets, goals and the decisions ahead.</p></div></section><section className="budgy-auth-panel"><div className="budgy-auth-card"><p className="budgy-eyebrow">Welcome to Budgy</p><h2>{mode==="signin"?"Sign in to your household":mode==="signup"?"Create your account":"Reset your password"}</h2><p>{mode==="forgot"?"We’ll send a secure reset link to your email.":"Each household member uses their own private account."}</p><form className="budgy-form" onSubmit={submit}>{mode==="signup"&&<label className="budgy-field"><span>What should we call you?</span><input autoFocus required autoComplete="name" value={displayName} onChange={(event)=>setDisplayName(event.target.value)}/></label>}<label className="budgy-field"><span>Email</span><input autoFocus={mode!=="signup"} type="email" autoComplete="email" required value={email} onChange={(event)=>setEmail(event.target.value)}/></label>{mode!=="forgot"&&<label className="budgy-field"><span>Password</span><input type="password" minLength={8} autoComplete={mode==="signin"?"current-password":"new-password"} required value={password} onChange={(event)=>setPassword(event.target.value)}/></label>}{message&&<p className="budgy-auth-message" role="status">{message}</p>}<button className="budgy-button budgy-button--primary" disabled={busy} type="submit">{busy?"Please wait…":mode==="signin"?"Sign in":mode==="signup"?"Sign up":"Send reset link"}</button></form><div className="budgy-auth-links">{mode!=="signin"?<button type="button" onClick={()=>{setMode("signin");setMessage("");}}>Back to sign in</button>:<><button type="button" onClick={()=>{setMode("signup");setMessage("");}}>Create an account</button><button type="button" onClick={()=>{setMode("forgot");setMessage("");}}>Forgot password?</button></>}</div></div></section></main>;
};
export const NewPassword:React.FC=()=>{const{updatePassword}=useAuth();const[password,setPassword]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);return <main className="budgy-auth budgy-auth--single"><section className="budgy-auth-card"><p className="budgy-eyebrow">Account recovery</p><h2>Choose a new password</h2><form className="budgy-form" onSubmit={async(event)=>{event.preventDefault();setBusy(true);try{await updatePassword(password);window.history.replaceState({},"","/budgy");setMessage("Password updated. You can continue to Budgy.");}catch(error){setMessage(friendly(error));}finally{setBusy(false);}}}><label className="budgy-field"><span>New password</span><input autoFocus type="password" minLength={8} required value={password} onChange={(event)=>setPassword(event.target.value)}/></label>{message&&<p className="budgy-auth-message">{message}</p>}<button className="budgy-button budgy-button--primary" disabled={busy}>Update password</button></form></section></main>;};
