import React,{useState}from"react";
import{householdRepository}from"../repositories/householdRepository";

const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map((byte)=>byte.toString(16).padStart(2,"0")).join("");
const inviteFromHash=()=>new URLSearchParams(window.location.hash.replace(/^#/,"")).get("invite")??sessionStorage.getItem("budgy.pendingInvite")??"";
export const Onboarding:React.FC<{onComplete:()=>void}>=({onComplete})=>{const token=inviteFromHash();const[mode,setMode]=useState<"choose"|"create"|"join">(token?"join":"choose");const[name,setName]=useState("");const[displayName,setDisplayName]=useState("");const[inviteToken,setInviteToken]=useState(token);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{if(mode==="create")await householdRepository.create(name,displayName);else await householdRepository.acceptInvite(await hash(inviteToken),displayName);sessionStorage.removeItem("budgy.pendingInvite");window.history.replaceState({},"",window.location.pathname);onComplete();}catch(reason){setError(reason instanceof Error?reason.message:"Onboarding could not be completed.");}finally{setBusy(false);}};
  return <main className="budgy-onboarding"><div className="budgy-brand"><span className="budgy-brand-mark">B</span><span className="budgy-brand-name">budgy</span></div><section className="budgy-onboarding-card"><p className="budgy-eyebrow">Welcome to Budgy</p><h1>{mode==="choose"?"Start your shared household":mode==="create"?"Create your household":"Join your household"}</h1>{mode==="choose"?<><p>Make a new household or join your partner through a secure invitation.</p><div className="budgy-onboarding-options"><button type="button" onClick={()=>setMode("create")}><b>Create a household</b><span>Set up a new shared financial plan</span></button><button type="button" onClick={()=>setMode("join")}><b>Join a household</b><span>Use the private link from your partner</span></button></div></>:<form className="budgy-form" onSubmit={submit}>{mode==="create"&&<label className="budgy-field"><span>Household name</span><input autoFocus required value={name} onChange={(event)=>setName(event.target.value)} placeholder="Our household"/></label>}<label className="budgy-field"><span>Your display name</span><input autoFocus={mode==="join"} required value={displayName} onChange={(event)=>setDisplayName(event.target.value)} placeholder="How your partner sees you"/></label>{mode==="join"&&!token&&<label className="budgy-field"><span>Invitation token</span><input required value={inviteToken} onChange={(event)=>setInviteToken(event.target.value)} /></label>}{error&&<p className="budgy-auth-message">{error}</p>}<div className="budgy-dialog-actions"><button className="budgy-button budgy-button--quiet" type="button" onClick={()=>setMode("choose")}>Back</button><button className="budgy-button budgy-button--primary" disabled={busy}>{busy?"Please wait…":mode==="create"?"Create household":"Join household"}</button></div></form>}</section></main>;
};
