import React, { useState } from "react";
import { Link } from "react-router-dom";
import Icon from "../components/Icon";
import { childAge } from "../domain/insights";
import { productConfig } from "../config/product";
import { useNestStore } from "../store/NestStore";
import { PreferenceCategory } from "../domain/types";
import { NEST_BASE_PATH } from "../config/product";

const Family: React.FC = () => {
  const { data, selectedChild, addPreference, updatePreference, removePreference, inviteMember } = useNestStore();
  const [editing, setEditing] = useState(false);
  const [category, setCategory] = useState<PreferenceCategory>("like");
  const [entry, setEntry] = useState("");
  const [editingPreferenceId, setEditingPreferenceId] = useState<string | null>(null);
  const [inviteEmail, setInviteEmail] = useState(""); const [inviteLink, setInviteLink] = useState("");
  const monthSpend = data.expenses.filter((expense) => expense.childId === selectedChild.id && new Date(expense.occurredAt).getMonth() === new Date().getMonth()).reduce((sum, expense) => sum + expense.amountPence, 0);
  return <div className="nest-page nest-family"><header className="nest-page-heading"><div><p>YOUR FAMILY</p><h1>The people around {selectedChild.name}</h1></div><span>{data.household.name}</span></header>
    <div className="nest-family-grid"><section className="nest-profile-card"><div className="nest-profile-hero"><span>{selectedChild.initials}</span><div><h2>{selectedChild.name}</h2><p>{childAge(selectedChild)} old</p></div></div><div className="nest-preferences"><div className="nest-profile-subhead"><h3>What we know</h3><button type="button" onClick={() => { setEditing((value) => !value); setEditingPreferenceId(null); setEntry(""); }}>{editing ? "Done" : "Edit"}</button></div>{(["like", "dislike", "soothing", "routine", "note"] as PreferenceCategory[]).map((preferenceCategory) => <div key={preferenceCategory}><small>{preferenceCategory === "like" ? "Likes" : preferenceCategory === "dislike" ? "Doesn’t like" : preferenceCategory === "soothing" ? "Soothed by" : preferenceCategory === "routine" ? "Routine" : "Notes"}</small>{editing ? <div className="nest-preference-chips">{selectedChild.preferences.filter((item) => item.category === preferenceCategory).map((item) => <span key={item.id}><button type="button" onClick={() => { setEditingPreferenceId(item.id); setCategory(item.category); setEntry(item.label); }}>{item.label}</button><button type="button" aria-label={`Remove ${item.label}`} onClick={() => removePreference(item.id)}>×</button></span>)}</div> : <p>{selectedChild.preferences.filter((item) => item.category === preferenceCategory).map((item) => item.label).join(" · ") || "Still learning"}</p>}</div>)}{editing && <form className="nest-preference-form" onSubmit={(event) => { event.preventDefault(); if (entry.trim()) { if (editingPreferenceId) updatePreference(editingPreferenceId, entry.trim()); else addPreference(category, entry.trim()); setEditingPreferenceId(null); setEntry(""); } }}><select value={category} disabled={editingPreferenceId !== null} onChange={(event) => setCategory(event.target.value as PreferenceCategory)} aria-label="Entry category"><option value="like">Likes</option><option value="dislike">Doesn’t like</option><option value="soothing">Soothed by</option><option value="routine">Routine</option><option value="note">Note</option></select><input value={entry} onChange={(event) => setEntry(event.target.value)} placeholder="Add something your family knows"/><button type="submit" disabled={!entry.trim()}>{editingPreferenceId ? "Update" : "Add"}</button></form>}</div></section>
      <div><section className="nest-family-members"><div className="nest-section-title"><p>HOUSEHOLD</p><span>{data.users.length} members</span></div>{data.users.map((user, index) => <article key={user.id}><span>{user.displayName[0]}</span><div><strong>{user.displayName}</strong><small>{data.household.members.find((member) => member.userId === user.id)?.relationshipLabel ?? (index === 0 ? "Owner" : "Parent")}</small></div><em>{user.id === data.userPreferences.userId ? "You" : "Shared care"}</em></article>)}<form className="nest-family-invite" onSubmit={async(event) => { event.preventDefault(); const token = await inviteMember(inviteEmail); setInviteLink(token ? `${window.location.origin}/nest/join?token=${encodeURIComponent(token)}` : "Invitation links are available when Nest is connected to Supabase."); }}><label>Invite another parent<input type="email" required placeholder="partner@example.com" value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)}/></label><button type="submit">Create invite</button>{inviteLink && <code>{inviteLink}</code>}</form></section>
      <Link to={`${NEST_BASE_PATH}/handover`} className="nest-handover-link"><span><Icon name="handover"/></span><div><small>PARENT HANDOVER</small><strong>See what happened</strong><p>Feeds, sleep, nappies, medicine and needs.</p></div><Icon name="chevron"/></Link><section className="nest-money-preview"><span><Icon name="insights"/></span><div><small>Spent on {selectedChild.name} this month</small><strong>{new Intl.NumberFormat("en-GB", { style: "currency", currency: productConfig.currency }).format(monthSpend / 100)}</strong><p>Purchases automatically update this total.</p></div></section></div>
    </div>
  </div>;
};
export default Family;
