import React, { useMemo } from "react";
import { Link } from "react-router-dom";
import Icon from "../components/Icon";
import { NEST_BASE_PATH } from "../config/product";
import { formatDuration } from "../domain/insights";
import { generateInsights } from "../domain/intelligence/insights";
import { displayTime } from "../domain/intelligence/time";
import { useNestStore } from "../store/NestStore";

const clock = (date: Date): string => new Intl.DateTimeFormat("en-GB", { hour: "numeric", minute: "2-digit" }).format(date);
const Insights: React.FC = () => {
  const { data, selectedChild } = useNestStore(); const intelligence = useMemo(() => generateInsights(data.activities, selectedChild), [data.activities, selectedChild]); const primary = intelligence.insights[0];
  if (!intelligence.learning.ready) return <div className="nest-page nest-insights"><header className="nest-page-heading"><div><p>INSIGHTS FOR {selectedChild.name.toUpperCase()}</p><h1>Here’s what Nest is learning.</h1></div></header><section className="nest-learning"><span><Icon name="sparkle" size={28}/></span><p>NEST IS LEARNING {selectedChild.name.toUpperCase()}’S RHYTHM</p><h2>Keep logging the moments that already matter.</h2><div className="nest-learning-progress"><i style={{ width: `${Math.min(100, intelligence.learning.activeDays / 3 * 100)}%` }}/></div><strong>{intelligence.learning.activeDays} day{intelligence.learning.activeDays === 1 ? "" : "s"} of activity</strong><small>Feeds, sleep and nappies will gradually unlock useful, personal patterns. Nest won’t guess before it has enough evidence.</small></section></div>;
  return <div className="nest-page nest-insights"><header className="nest-page-heading"><div><p>INSIGHTS FOR {selectedChild.name.toUpperCase()}</p><h1>Here’s what we’re noticing.</h1></div><span>Compared with {selectedChild.name}’s own recent rhythm</span></header>
    {primary ? <Link className="nest-primary-insight" to={`${NEST_BASE_PATH}/insights/${primary.id}`}><span><Icon name={primary.category === "feeding" ? "feed" : primary.category === "sleep" ? "sleep" : "sparkle"}/></span><div><p>ONE THING TO KNOW</p><h2>{primary.title}</h2><strong>{primary.observation}</strong><small>Based on {primary.sampleSize} observations · {primary.period}</small></div><Icon name="chevron"/></Link> : <section className="nest-learning nest-learning-compact"><p>A PATTERN IS FORMING</p><h2>Nest has enough history to understand the rhythm, but nothing has changed enough to call out today.</h2><small>That’s useful too. No insight is better than a noisy one.</small></section>}
    {intelligence.insights.length > 1 && <section className="nest-secondary-insights"><div className="nest-section-title"><p>RECENT CHANGES</p><span>Explainable patterns</span></div>{intelligence.insights.slice(1).map((insight) => <Link key={insight.id} to={`${NEST_BASE_PATH}/insights/${insight.id}`}><span><Icon name={insight.category === "feeding" ? "feed" : insight.category === "sleep" ? "sleep" : "sparkle"}/></span><div><strong>{insight.title}</strong><small>{insight.observation}</small></div><Icon name="chevron"/></Link>)}</section>}
    <div className="nest-intelligence-grid"><section><div className="nest-section-title"><p>LIKELY NEXT</p><span>Typical windows, not promises</span></div>{intelligence.likelyNextFeed && <article><span className="terracotta"><Icon name="feed"/></span><div><small>LIKELY NEXT FEED</small><strong>{clock(intelligence.likelyNextFeed.low)}–{clock(intelligence.likelyNextFeed.high)}</strong></div></article>}{intelligence.likelyBedtime && <article><span className="sage"><Icon name="sleep"/></span><div><small>USUAL BEDTIME</small><strong>{intelligence.likelyBedtime.display}</strong></div></article>}</section>
      <section><div className="nest-section-title"><p>{selectedChild.name.toUpperCase()}’S RHYTHM</p><span>Last 14 days</span></div>{intelligence.rhythm.wakeWindow && <article><small>Morning wake</small><strong>{intelligence.rhythm.wakeWindow.display}</strong></article>}{intelligence.rhythm.firstNapWindow && <article><small>First nap</small><strong>~{Math.round(intelligence.baseline.firstNapAfterWakeMinutes!.median / 5) * 5}m after waking</strong></article>}{intelligence.rhythm.feedInterval && <article><small>Feeds</small><strong>Every {formatDuration(intelligence.rhythm.feedInterval.low * 60000)}–{formatDuration(intelligence.rhythm.feedInterval.high * 60000)}</strong></article>}{intelligence.rhythm.bedtimeWindow && <article><small>Bedtime</small><strong>{intelligence.rhythm.bedtimeWindow.display}</strong></article>}</section></div>
    <section className="nest-detail-stats"><div className="nest-section-title"><p>THE DETAIL</p><span>Useful data beneath the patterns</span></div><div>{intelligence.baseline.nighttimeSleepMinutes && <article><small>Typical nighttime sleep</small><strong>{formatDuration(intelligence.baseline.nighttimeSleepMinutes.median * 60000)}</strong></article>}{intelligence.baseline.bottleAmountMl && <article><small>Typical bottle</small><strong>{Math.round(intelligence.baseline.bottleAmountMl.median)}ml</strong></article>}{intelligence.baseline.nappiesPerDay && <article><small>Typical nappies</small><strong>{intelligence.baseline.nappiesPerDay.median.toFixed(1)}/day</strong></article>}{intelligence.baseline.bedtimeMinutes && <article><small>Median bedtime</small><strong>{displayTime(intelligence.baseline.bedtimeMinutes.median)}</strong></article>}</div></section>
  </div>;
};
export default Insights;
