import React, { useState } from "react";
import { useNestAuth } from "../auth/AuthProvider";
import { SupabaseNestRepository } from "../repositories/nestSupabaseRepository";

const relationships = ["Dad", "Mum", "Parent", "Guardian", "Other"];
const feedingChoices = ["Breastfeeding", "Expressed milk", "Formula", "Solids"];
const Onboarding: React.FC<{ repository: SupabaseNestRepository; onComplete(): void }> = ({ repository, onComplete }) => {
  const { user } = useNestAuth(); const [step, setStep] = useState(0); const [name, setName] = useState(() => String(user?.user_metadata.display_name ?? "")); const [relationship, setRelationship] = useState("Parent"); const [childName, setChildName] = useState(""); const [birthDate, setBirthDate] = useState(""); const [feeding, setFeeding] = useState<string[]>([]); const [inviteEmail, setInviteEmail] = useState(""); const [inviteLink, setInviteLink] = useState(""); const [householdId, setHouseholdId] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const create = async () => { setBusy(true); setError(""); try { await repository.updateProfile(name, relationship); await repository.createHousehold({ householdName: `${childName}’s family`, childName, birthDate, feeding, relationship }); const data = await repository.load(); setHouseholdId(data.household.id); setStep(5); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create your family space"); } finally { setBusy(false); } };
  const progress = Math.max(0, step) / 5 * 100;
  return <main className="nest-onboarding"><div className="nest-onboarding-top"><div className="nest-brand"><span className="nest-brand-mark">n</span><strong>Nest</strong></div><span>About 1 minute</span></div><div className="nest-onboarding-progress"><i style={{ width: `${progress}%` }}/></div><section>
    {step === 0 && <div className="nest-onboarding-welcome"><p>WELCOME TO NEST</p><h1>Care, shared.</h1><span>A calm place for the people raising your child together.</span><button type="button" onClick={() => setStep(1)}>Get started</button></div>}
    {step === 1 && <><p>ABOUT YOU</p><h1>What should we call you?</h1><label className="nest-onboarding-field">Your name<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Juwon"/></label><fieldset><legend>I am…</legend><div className="nest-onboarding-chips">{relationships.map((value) => <button type="button" className={relationship === value ? "is-active" : ""} key={value} onClick={() => setRelationship(value)}>{value}</button>)}</div></fieldset><button className="nest-onboarding-next" disabled={!name.trim()} onClick={() => setStep(2)}>Continue</button></>}
    {step === 2 && <><p>YOUR CHILD</p><h1>Let’s add your child.</h1><label className="nest-onboarding-field">Name<input autoFocus value={childName} onChange={(event) => setChildName(event.target.value)} placeholder="Maya"/></label><label className="nest-onboarding-field">Date of birth<input type="date" max={new Date().toISOString().slice(0,10)} value={birthDate} onChange={(event) => setBirthDate(event.target.value)}/></label><div className="nest-photo-placeholder"><span>+</span><div><strong>Add a photo</strong><small>Optional · available after setup</small></div></div><button className="nest-onboarding-next" disabled={!childName.trim() || !birthDate} onClick={() => setStep(3)}>Continue</button></>}
    {step === 3 && <><p>FEEDING</p><h1>How is {childName} currently fed?</h1><span className="nest-onboarding-intro">Choose all that apply. You can change this later.</span><div className="nest-feeding-options">{feedingChoices.map((value) => <button type="button" className={feeding.includes(value) ? "is-active" : ""} key={value} onClick={() => setFeeding((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value])}><i>{feeding.includes(value) ? "✓" : ""}</i><span>{value}</span></button>)}</div>{error && <p className="nest-form-error">{error}</p>}<button className="nest-onboarding-next" disabled={busy} onClick={() => void create()}>{busy ? "Creating your Nest…" : "Continue"}</button></>}
    {step === 5 && <><p>YOUR HOUSEHOLD</p><h1>Who else cares for {childName}?</h1><span className="nest-onboarding-intro">Invite them into the same private household. Email delivery isn’t configured yet, so Nest will create a secure development link.</span><label className="nest-onboarding-field">Their email<input type="email" value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)} placeholder="partner@example.com"/></label>{inviteLink && <div className="nest-invite-link"><small>Development invitation link</small><code>{inviteLink}</code></div>}{error && <p className="nest-form-error">{error}</p>}<button className="nest-onboarding-next" disabled={!inviteEmail.trim()} onClick={async() => { try { const token = await repository.invite(householdId, inviteEmail); setInviteLink(`${window.location.origin}/nest/join?token=${encodeURIComponent(token)}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create invitation"); } }}>Create invite link</button><button className="nest-onboarding-skip" type="button" onClick={onComplete}>{inviteLink ? "Enter Nest" : "I’ll do this later"}</button></>}
  </section></main>;
};
export default Onboarding;
