import{accountBalances}from"./accounts";
import{applyReallocation,calculateActualDebtPayments,calculateActualSpending,calculateAllocationProgress,calculateLeftToAllocate,calculateLeftToSpend,calculatePlannedDebtPayments,calculatePlannedSpending,calculateReallocationPreview,matchDebtPaymentAllocation,validateReallocation}from"./allocations";

const card={id:"amex",name:"Amex",owner:"u1",type:"credit_card",currency:"GBP",openingBalance:449115,creditLimit:1000000,isActive:true};
const bank={id:"bank",name:"Lloyds",owner:"u1",type:"current_account",currency:"GBP",openingBalance:1000000,isActive:true};
const spending={id:"personal",name:"Personal",group:"Personal",owner:"u1",amount:25000,recurring:true,trackActuals:true,purpose:"spending"};
const debt={id:"amex-plan",name:"Amex payoff",group:"Debt payments",owner:"household",amount:60000,recurring:true,trackActuals:true,purpose:"debt_payment",linkedAccountId:"amex"};
const plan={month:"2026-10",householdName:"Home",income:[{id:"income",name:"Income",owner:"u1",amount:750000,recurring:true}],savings:250000,budget:[spending,{...spending,id:"other",name:"Other spending",amount:363200},debt]};
const tx=(id,type,amount,overrides={})=>({id,type,amount,description:id,owner:"u1",date:"2026-10-10",budgetMonth:"2026-10",...overrides});

it("separates spending plans from debt-payment plans",()=>{expect(calculatePlannedSpending(plan)).toBe(388200);expect(calculatePlannedDebtPayments(plan)).toBe(60000);});
it("counts a linked card payment toward debt progress but never as spending",()=>{const payment=tx("payment","credit_card_payment",60000,{accountId:"bank",destinationAccountId:"amex",budgetItemId:"amex-plan"});expect(calculateActualDebtPayments([payment],"2026-10")).toBe(60000);expect(calculateActualSpending([payment],"2026-10")).toBe(0);expect(calculateAllocationProgress(debt,[payment],"2026-10")).toMatchObject({actual:60000,remaining:0,usedRate:1});expect(accountBalances([bank,card],[payment]).find((row)=>row.id==="amex").balance).toBe(389115);});
it("adds partial and multiple payments and shows an over-plan result without spending",()=>{const payments=[tx("one","credit_card_payment",25000,{accountId:"bank",destinationAccountId:"amex",budgetItemId:"amex-plan"}),tx("two","credit_card_payment",20000,{accountId:"bank",destinationAccountId:"amex",budgetItemId:"amex-plan"}),tx("three","credit_card_payment",30000,{accountId:"bank",destinationAccountId:"amex",budgetItemId:"amex-plan"})];expect(calculateAllocationProgress(debt,payments,"2026-10")).toMatchObject({actual:75000,remaining:-15000,usedRate:1.25});expect(calculateActualSpending(payments,"2026-10")).toBe(0);});
it("counts a card purchase once as spending and increases card debt",()=>{const purchase=tx("tesco","expense",5000,{accountId:"amex",budgetItemId:"personal",category:"Food"});expect(calculateActualSpending([purchase],"2026-10")).toBe(5000);expect(accountBalances([card],[purchase])[0].balance).toBe(454115);});
it("keeps left to spend independent from debt payments",()=>{const expense=tx("spent","expense",288300,{accountId:"bank",budgetItemId:"other"});const payment=tx("payment","credit_card_payment",40000,{accountId:"bank",destinationAccountId:"amex",budgetItemId:"amex-plan"});expect(calculateLeftToSpend(plan,[expense,payment],"2026-10")).toBe(99900);});
it("moves planned money without changing total allocation or transactions",()=>{const preview=calculateReallocationPreview(plan,[],"2026-10","personal","amex-plan",10000);const next=applyReallocation(plan,preview);expect(next.budget.find((row)=>row.id==="personal").amount).toBe(15000);expect(next.budget.find((row)=>row.id==="amex-plan").amount).toBe(70000);expect(next.budget.reduce((sum,row)=>sum+row.amount,0)).toBe(plan.budget.reduce((sum,row)=>sum+row.amount,0));});
it("assigns unallocated income to debt and reduces left to allocate",()=>{expect(calculateLeftToAllocate(plan)).toBe(51800);const preview=calculateReallocationPreview(plan,[],"2026-10",undefined,"amex-plan",20000);const next=applyReallocation(plan,preview);expect(calculateLeftToAllocate(next)).toBe(31800);expect(next.budget.find((row)=>row.id==="amex-plan").amount).toBe(80000);});
it("requires confirmation when moving a plan below recorded actuals",()=>{const spent=tx("spent","expense",22000,{accountId:"bank",budgetItemId:"personal"});const preview=calculateReallocationPreview(plan,[spent],"2026-10","personal","amex-plan",10000);expect(preview.wouldPutSourceOverPlan).toBe(true);expect(validateReallocation(preview).valid).toBe(false);expect(validateReallocation(preview,true).valid).toBe(true);});
it("matches a payment plan deterministically by destination card",()=>expect(matchDebtPaymentAllocation(plan,"amex").id).toBe("amex-plan"));
