import { accountBalances, spendingEffect } from "./accounts";
import { formatMoney } from "./money";
import { BudgyData, FinancialAccount, MonthlyPlan, Owner, Pence, Transaction } from "./types";

export interface ReportBreakdown { key:string; label:string; amount:Pence; percentage:number; planned?:Pence; difference?:Pence; transactionIds:string[]; }
export interface AccountMovement { accountId:string; name:string; type:FinancialAccount["type"]; opening:Pence; moneyIn:Pence; moneyOut:Pence; purchases:Pence; payments:Pence; refunds:Pence; closing:Pence; availableCredit?:Pence; complete:boolean; }
export interface MonthComparison { income:Pence; spending:Pence; savings:Pence; creditCardDebt:Pence; categoryChanges:Array<{key:string;amount:Pence}>; }
export interface MonthlyReport {
  month:string; transactionCount:number; income:Pence; spending:Pence; savings:Pence; netCashFlow:Pence;
  remainingBudget:Pence; savingsRate:number; budgetUtilisation:number; creditCardDebt:Pence; unallocatedMoney:Pence;
  plannedIncome:Pence; plannedSpending:Pence; plannedSavings:Pence;
  incomeBreakdown:ReportBreakdown[]; categories:ReportBreakdown[]; members:ReportBreakdown[]; planVsActual:ReportBreakdown[];
  accounts:AccountMovement[]; observations:string[]; comparison?:MonthComparison;
}

const inMonth=(transaction:Transaction,month:string)=>transaction.date.startsWith(month);
const monthEnd=(month:string)=>`${month}-31`;
const previousMonth=(month:string)=>{const[y,m]=month.split("-").map(Number);const date=new Date(y,m-2,1);return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`;};
const sum=(values:number[])=>values.reduce((total,value)=>total+value,0);

export const calculateActualIncome=(transactions:Transaction[],month:string)=>sum(transactions.filter((row)=>inMonth(row,month)&&row.type==="income").map((row)=>row.amount));
export const calculateActualSpending=(transactions:Transaction[],month:string)=>sum(transactions.filter((row)=>inMonth(row,month)).map(spendingEffect));
export const calculateActualSavings=(transactions:Transaction[],accounts:FinancialAccount[],month:string)=>{const savings=new Set(accounts.filter((account)=>account.type==="savings_account").map((account)=>account.id));return sum(transactions.filter((row)=>inMonth(row,month)).map((row)=>row.type==="transfer"?(savings.has(row.destinationAccountId??"")?row.amount:0)-(savings.has(row.accountId??"")?row.amount:0):0));};

const breakdown=(rows:Transaction[],key:(row:Transaction)=>string,label:(key:string)=>string):ReportBreakdown[]=>{const groups=new Map<string,{amount:number;ids:string[]}>();rows.forEach((row)=>{const group=key(row);const current=groups.get(group)??{amount:0,ids:[]};current.amount+=spendingEffect(row);current.ids.push(row.id);groups.set(group,current);});const denominator=sum(Array.from(groups.values()).map((entry)=>entry.amount));return Array.from(groups.entries()).map(([entryKey,value])=>({key:entryKey,label:label(entryKey),amount:value.amount,percentage:denominator===0?0:value.amount/denominator,transactionIds:value.ids})).filter((entry)=>entry.amount!==0).sort((a,b)=>b.amount-a.amount);};

export const calculateCategoryBreakdown=(transactions:Transaction[],plan:MonthlyPlan|undefined,month:string)=>{const actual=breakdown(transactions.filter((row)=>inMonth(row,month)&&(row.type==="expense"||row.type==="refund")),(row)=>row.category,(key)=>key);const keys=new Set([...actual.map((row)=>row.key),...(plan?.budget??[]).map((row)=>row.group)]);const total=sum(actual.map((row)=>row.amount));return Array.from(keys).map((key)=>{const found=actual.find((row)=>row.key===key);const planned=sum((plan?.budget??[]).filter((item)=>item.group===key).map((item)=>item.amount));const amount=found?.amount??0;return{key,label:key,amount,percentage:total?amount/total:0,planned,difference:planned-amount,transactionIds:found?.transactionIds??[]};}).sort((a,b)=>b.amount-a.amount);};
export const calculateMemberBreakdown=(transactions:Transaction[],month:string,memberName:(owner:Owner)=>string)=>breakdown(transactions.filter((row)=>inMonth(row,month)&&(row.type==="expense"||row.type==="refund")),(row)=>row.owner,memberName);

const accountDelta=(account:FinancialAccount,row:Transaction)=>{if(account.type==="credit_card"){if(row.type==="expense"&&row.accountId===account.id)return row.amount;if(row.type==="refund"&&row.accountId===account.id)return-row.amount;if(row.type==="credit_card_payment"&&row.destinationAccountId===account.id)return-row.amount;return 0;}if(row.type==="income"&&row.accountId===account.id)return row.amount;if(row.type==="refund"&&row.accountId===account.id)return row.amount;if((row.type==="expense"||row.type==="transfer"||row.type==="credit_card_payment")&&row.accountId===account.id)return-row.amount;if(row.type==="transfer"&&row.destinationAccountId===account.id)return row.amount;return 0;};
export const calculateAccountMovement=(account:FinancialAccount,transactions:Transaction[],month:string):AccountMovement=>{const before=transactions.filter((row)=>row.date<`${month}-01`);const rows=transactions.filter((row)=>inMonth(row,month));const opening=account.openingBalance+sum(before.map((row)=>accountDelta(account,row)));const purchases=sum(rows.filter((row)=>row.type==="expense"&&row.accountId===account.id).map((row)=>row.amount));const refunds=sum(rows.filter((row)=>row.type==="refund"&&row.accountId===account.id).map((row)=>row.amount));const payments=sum(rows.filter((row)=>row.type==="credit_card_payment"&&row.destinationAccountId===account.id).map((row)=>row.amount));const moneyIn=sum(rows.map((row)=>Math.max(accountDelta(account,row),0)));const moneyOut=sum(rows.map((row)=>Math.max(-accountDelta(account,row),0)));const closing=opening+moneyIn-moneyOut;return{accountId:account.id,name:account.name,type:account.type,opening,moneyIn,moneyOut,purchases,payments,refunds,closing,availableCredit:account.type==="credit_card"&&account.creditLimit!==undefined?account.creditLimit-closing:undefined,complete:account.openingBalance!==0||before.length>0};};

const rawMonth=(data:BudgyData,month:string)=>{const transactions=data.transactions.filter((row)=>inMonth(row,month));const income=calculateActualIncome(data.transactions,month);const spending=calculateActualSpending(data.transactions,month);const savings=calculateActualSavings(data.transactions,data.accounts,month);const debt=accountBalances(data.accounts,data.transactions.filter((row)=>row.date<=monthEnd(month))).filter((row)=>row.type==="credit_card").reduce((total,row)=>total+row.balance,0);return{transactions,income,spending,savings,debt};};
export const calculateMonthComparison=(data:BudgyData,month:string):MonthComparison|undefined=>{const previousKey=previousMonth(month);const previous=rawMonth(data,previousKey);if(!previous.transactions.length)return undefined;const current=rawMonth(data,month);const currentCategories=calculateCategoryBreakdown(data.transactions,data.months[month],month);const previousCategories=calculateCategoryBreakdown(data.transactions,data.months[previousKey],previousKey);const keys=new Set([...currentCategories.map((row)=>row.key),...previousCategories.map((row)=>row.key)]);const categoryChanges=Array.from(keys).map((key)=>({key,amount:(currentCategories.find((row)=>row.key===key)?.amount??0)-(previousCategories.find((row)=>row.key===key)?.amount??0)})).filter((row)=>row.amount!==0).sort((a,b)=>Math.abs(b.amount)-Math.abs(a.amount));return{income:current.income-previous.income,spending:current.spending-previous.spending,savings:current.savings-previous.savings,creditCardDebt:current.debt-previous.debt,categoryChanges};};

export const generateMonthObservations=(report:Omit<MonthlyReport,"observations">):string[]=>{const observations:string[]=[];if(report.income)observations.push(`You received ${formatMoney(report.income)} in recorded income this month.`);if(report.spending)observations.push(`${formatMoney(report.spending)} was recorded as spending.`);const strongest=report.planVsActual.filter((row)=>row.planned&&row.amount).sort((a,b)=>Math.abs(b.difference??0)-Math.abs(a.difference??0))[0];if(strongest){const difference=strongest.difference??0;observations.push(`${strongest.label} finished ${formatMoney(Math.abs(difference))} ${difference>=0?"below":"above"} the planned ${formatMoney(strongest.planned??0)} budget.`);}if(report.savings)observations.push(`${formatMoney(report.savings)} moved into savings accounts.`);if(report.comparison?.creditCardDebt)observations.push(`Credit-card debt ${report.comparison.creditCardDebt<0?"decreased":"increased"} by ${formatMoney(Math.abs(report.comparison.creditCardDebt))} compared with the previous month.`);observations.push(`${formatMoney(report.unallocatedMoney)} remained unallocated in the monthly plan.`);return observations;};

export const buildMonthlyReport=(data:BudgyData,month:string,memberName:(owner:Owner)=>string):MonthlyReport=>{const plan=data.months[month];const raw=rawMonth(data,month);const plannedIncome=sum((plan?.income??[]).map((row)=>row.amount));const plannedSpending=sum((plan?.budget??[]).map((row)=>row.amount));const plannedSavings=plan?.savings??0;const categories=calculateCategoryBreakdown(data.transactions,plan,month);const members=calculateMemberBreakdown(data.transactions,month,memberName);const planVsActual=categories;const allocatedActual=sum(raw.transactions.filter((row)=>row.budgetItemId&&(row.type==="expense"||row.type==="refund")).map(spendingEffect));const trackedPlanned=sum((plan?.budget??[]).filter((row)=>row.trackActuals!==false).map((row)=>row.amount));const incomeRows=raw.transactions.filter((row)=>row.type==="income");const incomeTotal=sum(incomeRows.map((row)=>row.amount));const incomeBreakdown=incomeRows.map((row)=>({key:row.id,label:`${row.description} · ${memberName(row.owner)}`,amount:row.amount,percentage:incomeTotal?row.amount/incomeTotal:0,transactionIds:[row.id]}));const base={month,transactionCount:raw.transactions.length,income:raw.income,spending:raw.spending,savings:raw.savings,netCashFlow:raw.income-raw.spending,remainingBudget:trackedPlanned-allocatedActual,savingsRate:raw.income?raw.savings/raw.income:0,budgetUtilisation:trackedPlanned?allocatedActual/trackedPlanned:0,creditCardDebt:raw.debt,unallocatedMoney:plannedIncome-plannedSpending-plannedSavings,plannedIncome,plannedSpending,plannedSavings,incomeBreakdown,categories,members,planVsActual,accounts:data.accounts.map((account)=>calculateAccountMovement(account,data.transactions,month)),comparison:calculateMonthComparison(data,month)};return{...base,observations:generateMonthObservations(base)};};
