import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState} from "react";
import {createDemoData} from "../data/demo";
import {calculateMacroTarget} from "../domain/nutrition";
import {compressWorkout,generateWorkout} from "../domain/training";
import {GroceryCheck,Measurement,Readiness,UserProfile,VelaData,Workout} from "../domain/types";
import {LocalVelaRepository,VelaRepository} from "../repositories/velaRepository";

export type SyncStatus="saved"|"saving"|"offline"|"error";
interface Toast{message:string;action?:string;onAction?:()=>void}
interface StoreValue{data:VelaData;today:Workout;toast:Toast|null;syncStatus:SyncStatus;updateProfile(profile:UserProfile):void;updateWorkout(workout:Workout):void;startWorkout(id:string):void;completeSet(workoutId:string,exerciseId:string,setId:string,reps:number,weight:number,rir?:number):void;undoSet(workoutId:string,exerciseId:string,setId:string):void;completeWorkout(id:string):void;replaceExercise(workoutId:string,itemId:string,exerciseId:string):void;adjustTime(minutes:number):void;saveReadiness(readiness:Readiness):void;replaceMeal(mealId:string,recipeId:string):void;toggleMeal(mealId:string):void;setServing(mealId:string,servings:number):void;addQuickFood(calories:number,protein:number,carbs:number,fat:number):void;addWater(amount:number):void;addMeasurement(value:Omit<Measurement,"id"|"date">):void;toggleGrocery(key:string):void;resetDemo():void;dismissToast():void}
interface ProviderProps{repository?:VelaRepository;initialData?:VelaData;onPersist?:(data:VelaData)=>Promise<void>;onClearSensitiveState?:()=>void}
const Context=createContext<StoreValue|null>(null);const todayKey=()=>new Date().toISOString().slice(0,10);
export const VelaStoreProvider:React.FC<React.PropsWithChildren<ProviderProps>>=({children,repository,initialData,onPersist})=>{const local=useRef<VelaRepository>(repository??(initialData?{load:()=>initialData,save:()=>undefined,clear:()=>undefined}:new LocalVelaRepository()));const[data,setData]=useState(()=>initialData??local.current.load());const[toast,setToast]=useState<Toast|null>(null);const[syncStatus,setSyncStatus]=useState<SyncStatus>("saved");const syncVersion=useRef(0);const pendingSync=useRef<VelaData|null>(null);
 const persist=useCallback((next:VelaData)=>{local.current.save(next);if(!onPersist)return;const version=++syncVersion.current;pendingSync.current=next;setSyncStatus(navigator.onLine?"saving":"offline");void onPersist(next).then(()=>{if(version===syncVersion.current){pendingSync.current=null;setSyncStatus("saved");}}).catch(()=>{if(version===syncVersion.current)setSyncStatus(navigator.onLine?"error":"offline");});},[onPersist]);useEffect(()=>{if(!onPersist)return;const retry=()=>{const pending=pendingSync.current;if(!pending)return;setSyncStatus("saving");void onPersist(pending).then(()=>{if(pendingSync.current===pending){pendingSync.current=null;setSyncStatus("saved");}}).catch(()=>setSyncStatus("error"));};window.addEventListener("online",retry);return()=>window.removeEventListener("online",retry);},[onPersist]);
 const commit=useCallback((update:(current:VelaData)=>VelaData)=>setData((current)=>{const next=update(current);persist(next);return next;}),[persist]);
 const ensureToday=useCallback((source:VelaData)=>source.workouts.find((item)=>item.date===todayKey()&&item.status!=="complete")??generateWorkout(source.profile,source.workouts.filter((item)=>item.status==="complete").length%source.profile.daysPerWeek,new Date()),[]);const today=ensureToday(data);
 const updateWorkout=useCallback((workout:Workout)=>commit((current)=>({...current,workouts:current.workouts.some((item)=>item.id===workout.id)?current.workouts.map((item)=>item.id===workout.id?workout:item):[workout,...current.workouts]})),[commit]);
 const updateProfile=useCallback((profile:UserProfile)=>commit((current)=>{const nextWorkout=generateWorkout(profile,0,new Date());const recipeIds=profile.diet==="vegan"?["tofu-scramble","tempeh-bowl","lentil-curry","protein-smoothie"]:["yoghurt-oats","chicken-rice","salmon-potato","protein-smoothie"];const meals=current.meals.length?current.meals:recipeIds.map((recipeId,index)=>({id:`meal-${todayKey()}-${index}`,recipeId,servings:1,eaten:false,date:todayKey()}));return{...current,profile,macros:calculateMacroTarget(profile),meals,workouts:[nextWorkout,...current.workouts.filter((item)=>item.date!==todayKey())]};}),[commit]);
 const startWorkout=useCallback((id:string)=>commit((current)=>({...current,workouts:(current.workouts.some((w)=>w.id===id)?current.workouts:[ensureToday(current),...current.workouts]).map((w)=>w.id===id?{...w,status:"active",startedAt:w.startedAt??new Date().toISOString()}:w)})),[commit,ensureToday]);
 const undoSet=useCallback((workoutId:string,exerciseId:string,setId:string)=>commit((current)=>({...current,workouts:current.workouts.map((workout)=>workout.id!==workoutId?workout:{...workout,exercises:workout.exercises.map((item)=>item.id!==exerciseId?item:{...item,sets:item.sets.map((set)=>set.id===setId?{...set,completedReps:undefined,completedWeightKg:undefined,rir:undefined,completedAt:undefined}:set)})})})),[commit]);
 const completeSet=useCallback((workoutId:string,exerciseId:string,setId:string,reps:number,weight:number,rir?:number)=>{commit((current)=>({...current,workouts:current.workouts.map((workout)=>workout.id!==workoutId?workout:{...workout,status:"active",startedAt:workout.startedAt??new Date().toISOString(),exercises:workout.exercises.map((item)=>item.id!==exerciseId?item:{...item,sets:item.sets.map((set)=>set.id===setId?{...set,completedReps:reps,completedWeightKg:weight,rir,completedAt:new Date().toISOString()}:set)})})}));setToast({message:"Set complete",action:"Undo",onAction:()=>undoSet(workoutId,exerciseId,setId)});},[commit,undoSet]);
 const completeWorkout=useCallback((id:string)=>{commit((current)=>({...current,streak:current.streak+1,workouts:current.workouts.map((item)=>item.id===id?{...item,status:"complete",completedAt:new Date().toISOString()}:item)}));setToast({message:"Workout saved — strong work."});},[commit]);
 const replaceExercise=useCallback((workoutId:string,itemId:string,exerciseId:string)=>commit((current)=>({...current,workouts:current.workouts.map((workout)=>workout.id===workoutId?{...workout,exercises:workout.exercises.map((item)=>item.id===itemId?{...item,exerciseId,sets:item.sets.map((set)=>({...set,id:`${exerciseId}-${set.id.split("-").pop()}`}))}:item)}:workout)})),[commit]);
 const adjustTime=useCallback((minutes:number)=>{updateWorkout(compressWorkout(today,minutes));setToast({message:`Today’s session adapted to ${minutes} minutes.`});},[today,updateWorkout]);
 const saveReadiness=useCallback((readiness:Readiness)=>commit((current)=>({...current,readiness:[readiness,...current.readiness.filter((item)=>item.date!==readiness.date)]})),[commit]);
 const replaceMeal=useCallback((mealId:string,recipeId:string)=>commit((current)=>({...current,meals:current.meals.map((meal)=>meal.id===mealId?{...meal,recipeId}:meal)})),[commit]);
 const toggleMeal=useCallback((mealId:string)=>commit((current)=>({...current,meals:current.meals.map((meal)=>meal.id===mealId?{...meal,eaten:!meal.eaten}:meal)})),[commit]);
 const setServing=useCallback((mealId:string,servings:number)=>commit((current)=>({...current,meals:current.meals.map((meal)=>meal.id===mealId?{...meal,servings:Math.max(.5,servings)}:meal)})),[commit]);
 const updateNutritionDay=useCallback((update:(day:VelaData["nutritionDays"][number])=>VelaData["nutritionDays"][number])=>commit((current)=>{const date=todayKey();const existing=current.nutritionDays.find((day)=>day.date===date)??{date,extraCalories:0,extraProtein:0,extraCarbs:0,extraFat:0,waterMl:0};return{...current,nutritionDays:[update(existing),...current.nutritionDays.filter((day)=>day.date!==date)]};}),[commit]);
 const addQuickFood=useCallback((calories:number,protein:number,carbs:number,fat:number)=>{updateNutritionDay((day)=>({...day,extraCalories:day.extraCalories+calories,extraProtein:day.extraProtein+protein,extraCarbs:day.extraCarbs+carbs,extraFat:day.extraFat+fat}));setToast({message:"Food added to today"});},[updateNutritionDay]);
 const addWater=useCallback((amount:number)=>{updateNutritionDay((day)=>({...day,waterMl:day.waterMl+amount}));setToast({message:`${amount} ml water logged`});},[updateNutritionDay]);
 const addMeasurement=useCallback((value:Omit<Measurement,"id"|"date">)=>{commit((current)=>({...current,measurements:[...current.measurements,{...value,id:`measure-${Date.now()}`,date:todayKey()}]}));setToast({message:"Measurement logged"});},[commit]);
 const toggleGrocery=useCallback((key:string)=>commit((current)=>{const found=current.groceryChecks.find((item)=>item.key===key);const groceryChecks:GroceryCheck[]=found?current.groceryChecks.map((item)=>item.key===key?{...item,checked:!item.checked}:item):[...current.groceryChecks,{key,checked:true}];return{...current,groceryChecks};}),[commit]);
 const resetDemo=useCallback(()=>{const next=createDemoData();local.current.save(next);setData(next);setToast({message:"Demo data restored"});},[]);
 const value=useMemo(()=>({data,today,toast,syncStatus,updateProfile,updateWorkout,startWorkout,completeSet,undoSet,completeWorkout,replaceExercise,adjustTime,saveReadiness,replaceMeal,toggleMeal,setServing,addQuickFood,addWater,addMeasurement,toggleGrocery,resetDemo,dismissToast:()=>setToast(null)}),[data,today,toast,syncStatus,updateProfile,updateWorkout,startWorkout,completeSet,undoSet,completeWorkout,replaceExercise,adjustTime,saveReadiness,replaceMeal,toggleMeal,setServing,addQuickFood,addWater,addMeasurement,toggleGrocery,resetDemo]);return <Context.Provider value={value}>{children}</Context.Provider>;};
export const useVela=()=>{const value=useContext(Context);if(!value)throw new Error("useVela must be used within VelaStoreProvider");return value;};
